/* Contenido extra A–F: situaciones, entrevista, phrasals, oído por nivel, -ed del plan */
window.ENLAB = window.ENLAB || {};

ENLAB.phrasesSituation = {
  airport: [
    { en: "Where is gate twelve?", es: "¿Dónde está la puerta 12?", min: 2 },
    { en: "Is this the line for security?", es: "¿Esta es la fila de seguridad?", min: 2 },
    { en: "My flight is delayed.", es: "Mi vuelo está retrasado.", min: 2 },
    { en: "I have a connecting flight.", es: "Tengo un vuelo de conexión.", min: 3 },
    { en: "Where do I pick up my bags?", es: "¿Dónde recojo las maletas?", min: 2 },
    { en: "Do I need a visa?", es: "¿Necesito visa?", min: 2 },
    { en: "Window or aisle?", es: "¿Ventana o pasillo?", min: 2 },
    { en: "I'd like an aisle seat, please.", es: "Quisiera asiento de pasillo.", min: 2 },
    { en: "How long is the layover?", es: "¿Cuánto dura la escala?", min: 3 },
    { en: "Which terminal is it?", es: "¿Qué terminal es?", min: 2 },
    { en: "I missed my connection.", es: "Perdí mi conexión.", min: 3 },
    { en: "Can you help me rebook?", es: "¿Me ayudas a reservar de nuevo?", min: 3 },
    { en: "Is boarding open yet?", es: "¿Ya abrieron embarque?", min: 2 },
    { en: "My passport is in my bag.", es: "Mi pasaporte está en la maleta.", min: 2 },
    { en: "I'm traveling for work.", es: "Viajo por trabajo.", min: 2 },
    { en: "Is there a lounge I can use?", es: "¿Hay lounge que pueda usar?", min: 3 },
    { en: "My bag didn't arrive.", es: "Mi maleta no llegó.", min: 2 },
    { en: "Can I get a meal voucher?", es: "¿Me das un voucher de comida?", min: 3 },
    { en: "Where is the taxi stand?", es: "¿Dónde está el taxi?", min: 1 },
    { en: "I need an exit row, please.", es: "Quisiera fila de salida.", min: 3 },
  ],
  doctor: [
    { en: "I have a headache.", es: "Me duele la cabeza.", min: 2 },
    { en: "It hurts when I swallow.", es: "Me duele al tragar.", min: 3 },
    { en: "I've had a fever since yesterday.", es: "Tengo fiebre desde ayer.", min: 3 },
    { en: "I'm allergic to penicillin.", es: "Soy alérgico a la penicilina.", min: 3 },
    { en: "How often should I take this?", es: "¿Cada cuánto tomo esto?", min: 2 },
    { en: "Do I need a prescription?", es: "¿Necesito receta?", min: 3 },
    { en: "I've been coughing for three days.", es: "Llevo tres días tosiendo.", min: 3 },
    { en: "I feel dizzy.", es: "Me siento mareado.", min: 2 },
    { en: "It started last night.", es: "Empezó anoche.", min: 2 },
    { en: "Should I rest today?", es: "¿Debería descansar hoy?", min: 3 },
    { en: "Is it serious?", es: "¿Es grave?", min: 2 },
    { en: "I need to see a doctor.", es: "Necesito ver a un médico.", min: 2 },
    { en: "My stomach hurts.", es: "Me duele el estómago.", min: 2 },
    { en: "I can't sleep well.", es: "No duermo bien.", min: 2 },
    { en: "Thank you for your help.", es: "Gracias por su ayuda.", min: 1 },
    { en: "Can I get a sick note?", es: "¿Me das una incapacidad?", min: 3 },
    { en: "Should I come back if it gets worse?", es: "¿Vuelvo si empeora?", min: 3 },
    { en: "I need a refill.", es: "Necesito recarga de la receta.", min: 3 },
    { en: "Is this contagious?", es: "¿Es contagioso?", min: 2 },
  ],
  workChat: [
    { en: "Hi team, quick update.", es: "Hola equipo, update rápido.", min: 3 },
    { en: "I'll follow up tomorrow.", es: "Hago follow up mañana.", min: 3 },
    { en: "Can we sync at three?", es: "¿Nos sincronizamos a las tres?", min: 3 },
    { en: "I'm out of office today.", es: "Estoy fuera de oficina hoy.", min: 3 },
    { en: "Let me loop you in.", es: "Te meto en el hilo.", min: 3 },
    { en: "Thanks for the heads-up.", es: "Gracias por avisar.", min: 3 },
    { en: "I'll get back to you by EOD.", es: "Te respondo al cierre del día.", min: 3 },
    { en: "Does this work for you?", es: "¿Te funciona?", min: 2 },
    { en: "Sorry for the late reply.", es: "Perdón por responder tarde.", min: 2 },
    { en: "Can you share the link?", es: "¿Compartes el enlace?", min: 2 },
    { en: "I'm on a call right now.", es: "Estoy en una llamada.", min: 2 },
    { en: "Let's take this offline.", es: "Hablemos fuera del chat.", min: 3 },
    { en: "I'll ping you on Slack.", es: "Te escribo en Slack.", min: 3 },
    { en: "Could you clarify that?", es: "¿Lo aclaras?", min: 3 },
    { en: "Sounds good to me.", es: "Me parece bien.", min: 2 },
    { en: "I'll look into it.", es: "Lo reviso.", min: 3 },
    { en: "We're blocked on this.", es: "Estamos bloqueados en esto.", min: 3 },
    { en: "I'll send a summary.", es: "Mando un resumen.", min: 3 },
    { en: "Can we push this to tomorrow?", es: "¿Lo pasamos a mañana?", min: 3 },
    { en: "I'll take notes and share them.", es: "Tomo notas y las comparto.", min: 3 },
  ],
  pharmacy: [
    { en: "I'd like to fill this prescription.", es: "Quiero surtir esta receta.", min: 2 },
    { en: "Do you have this over the counter?", es: "¿Esto es de venta libre?", min: 3 },
    { en: "I'm looking for ibuprofen.", es: "Busco ibuprofeno.", min: 2 },
    { en: "Does this cause drowsiness?", es: "¿Esto da sueño?", min: 3 },
    { en: "Can I take this with food?", es: "¿Lo tomo con comida?", min: 2 },
    { en: "I need something for a cough.", es: "Necesito algo para la tos.", min: 2 },
    { en: "Is there a generic version?", es: "¿Hay genérico?", min: 3 },
    { en: "How much is the copay?", es: "¿Cuánto es el copago?", min: 3 },
    { en: "My insurance isn't covering this.", es: "El seguro no lo cubre.", min: 3 },
    { en: "Can you recommend a pharmacist?", es: "¿Hay un farmacéutico?", min: 2 },
    { en: "I need it as soon as possible.", es: "Lo necesito lo antes posible.", min: 2 },
    { en: "Are there any side effects?", es: "¿Hay efectos secundarios?", min: 3 },
  ],
  school: [
    { en: "Where is the main office?", es: "¿Dónde está la oficina?", min: 1 },
    { en: "I'm here to pick up my child.", es: "Vengo a recoger a mi hijo.", min: 2 },
    { en: "What time does class start?", es: "¿A qué hora empieza la clase?", min: 1 },
    { en: "Can I speak with the teacher?", es: "¿Puedo hablar con el maestro?", min: 2 },
    { en: "She has a fever. She's staying home.", es: "Tiene fiebre. Se queda en casa.", min: 2 },
    { en: "Do you need a doctor's note?", es: "¿Necesitan receta / nota médica?", min: 3 },
    { en: "When is parent-teacher night?", es: "¿Cuándo es la junta de padres?", min: 3 },
    { en: "He forgot his homework.", es: "Olvidó la tarea.", min: 2 },
    { en: "Is there after-school care?", es: "¿Hay cuidado después de clase?", min: 3 },
    { en: "How do I sign the permission slip?", es: "¿Cómo firmo el permiso?", min: 3 },
    { en: "The bus was late this morning.", es: "El bus llegó tarde.", min: 2 },
    { en: "She's in third grade.", es: "Está en tercero.", min: 2 },
  ],
};

ENLAB.dialogsA2Tense = [
  { tag: "past", a: { en: "What did you do yesterday?", es: "¿Qué hiciste ayer?" }, b: { en: "I went to the gym. Then I stayed home.", es: "Fui al gym. Luego me quedé en casa." } },
  { tag: "going", a: { en: "Are you going to come?", es: "¿Vas a venir?" }, b: { en: "Yes, I'm going to come at six.", es: "Sí, voy a ir a las seis." } },
  { tag: "past", a: { en: "Did you finish it?", es: "¿Lo terminaste?" }, b: { en: "Not yet. I need more time.", es: "Todavía no. Necesito más tiempo." } },
  { tag: "perfect", a: { en: "Have you ever tried that?", es: "¿Alguna vez lo probaste?" }, b: { en: "I've never tried that.", es: "Nunca lo he probado." } },
  { tag: "past", a: { en: "Where did you go?", es: "¿Adónde fuiste?" }, b: { en: "I went home.", es: "Me fui a casa." } },
  { tag: "going", a: { en: "What are you going to do?", es: "¿Qué vas a hacer?" }, b: { en: "I'm going to study English.", es: "Voy a estudiar inglés." } },
  { tag: "perfect", a: { en: "Have you seen it?", es: "¿Lo has visto?" }, b: { en: "Yes, I've already seen it.", es: "Sí, ya lo vi. (experiencia → have)" } },
  { tag: "past", a: { en: "Did you like it?", es: "¿Te gustó?" }, b: { en: "I liked it a lot.", es: "Me gustó mucho." } },
  { tag: "going", a: { en: "When are you going to leave?", es: "¿Cuándo te vas?" }, b: { en: "I'm going to leave at eight.", es: "Me voy a las ocho." } },
  { tag: "perfect", a: { en: "Have you finished yet?", es: "¿Ya terminaste?" }, b: { en: "I've almost finished.", es: "Casi termino." } },
];

ENLAB.phrasalsWork = [
  { en: "I'll look it up.", es: "Lo busco (Google, docs).", say: "I'll look it up.", min: 3 },
  { en: "We need to figure it out.", es: "Hay que resolverlo.", say: "We need to figure it out.", min: 3 },
  { en: "I'll follow up with you.", es: "Te hago seguimiento.", say: "I'll follow up with you.", min: 3 },
  { en: "Let's wrap up.", es: "Cerremos / terminemos.", say: "Let's wrap up.", min: 3 },
  { en: "Can you fill me in?", es: "¿Me pones al día?", say: "Can you fill me in?", min: 3 },
  { en: "I'll hand it off to QA.", es: "Se lo paso a QA.", say: "I'll hand it off to QA.", min: 4 },
  { en: "We rolled it out last week.", es: "Lo desplegamos la semana pasada.", say: "We rolled it out last week.", min: 4 },
  { en: "The server went down.", es: "El servidor se cayó.", say: "The server went down.", min: 3 },
  { en: "I'll set up a meeting.", es: "Agendo una reunión.", say: "I'll set up a meeting.", min: 3 },
  { en: "Please turn it on.", es: "Enciéndelo / actívalo.", say: "Please turn it on.", min: 2 },
  { en: "We ran out of time.", es: "Se nos acabó el tiempo.", say: "We ran out of time.", min: 3 },
  { en: "I'll get back to you.", es: "Te respondo luego.", say: "I'll get back to you.", min: 3 },
  { en: "Can you hold on a second?", es: "¿Me esperas un segundo?", say: "Can you hold on a second?", min: 2 },
  { en: "Let's pick this up tomorrow.", es: "Lo retomamos mañana.", say: "Let's pick this up tomorrow.", min: 3 },
  { en: "I'll back you up in the meeting.", es: "Te apoyo en la junta.", say: "I'll back you up in the meeting.", min: 4 },
  { en: "We need to cut back on costs.", es: "Hay que recortar costos.", say: "We need to cut back on costs.", min: 4 },
  { en: "Don't give up yet.", es: "No te rindas aún.", say: "Don't give up yet.", min: 2 },
  { en: "I'll point it out in the doc.", es: "Lo marco en el documento.", say: "I'll point it out in the doc.", min: 3 },
];

ENLAB.interviewSim = [
  { q: "Tell me about yourself.", es: "Cuéntame de ti.", hint: "30 s: rol actual + una fortaleza.", min: 3 },
  { q: "Why are you interested in this role?", es: "¿Por qué te interesa?", hint: "Conecta con el puesto, no genérico.", min: 3 },
  { q: "What's your biggest strength?", es: "¿Tu mayor fortaleza?", hint: "Un ejemplo concreto.", min: 3 },
  { q: "What's a weakness you're working on?", es: "¿Una debilidad?", hint: "Real + qué haces para mejorar.", min: 3 },
  { q: "Describe a challenge you solved.", es: "Un reto que resolviste.", hint: "Situación → acción → resultado.", min: 3 },
  { q: "Where do you see yourself in five years?", es: "¿Dónde te ves en 5 años?", hint: "Crecimiento, no solo cargo.", min: 3 },
  { q: "Why should we hire you?", es: "¿Por qué contratarte?", hint: "2 razones + ejemplo.", min: 3 },
  { q: "Do you have any questions for us?", es: "¿Preguntas para nosotros?", hint: "Pregunta sobre el equipo o el día a día.", min: 3 },
  { q: "Tell me about a time you worked on a team.", es: "Cuéntame de un trabajo en equipo.", hint: "STAR: situación, tarea, acción, resultado.", min: 3 },
  { q: "How do you handle stress?", es: "¿Cómo manejas el estrés?", hint: "Ejemplo concreto + qué haces hoy.", min: 3 },
];

/* Pares preferidos por nivel en quiz oído */
ENLAB.earLevelTags = {
  1: /E muda|i corta vs ii|i vs ii|ä vs ei/i,
  2: /E muda|i vs ii|ship|sheep|live|leave/i,
  3: /ship|sheep|can|TH|V vs|very|berry|think|sink/i,
  4: /ship|CH|Z|NG|record|live|read/i,
};

/* 5 regulares extra por día del plan (índice 0–20) */
ENLAB.planEdFocus = [
  ["work", "live", "like", "need", "ask"],
  ["play", "want", "start", "help", "open"],
  ["close", "stop", "miss", "love", "clean"],
  ["watch", "listen", "answer", "call", "walk"],
  ["talk", "look", "turn", "move", "change"],
  ["work", "live", "play", "want", "need"],
  ["like", "ask", "start", "help", "open"],
  ["close", "stop", "miss", "love", "clean"],
  ["watch", "listen", "answer", "call", "walk"],
  ["talk", "look", "turn", "move", "change"],
  ["work", "live", "play", "want", "need"],
  ["like", "ask", "start", "help", "open"],
  ["close", "stop", "miss", "love", "clean"],
  ["watch", "listen", "answer", "call", "walk"],
  ["talk", "look", "turn", "move", "change"],
  ["work", "live", "play", "want", "need"],
  ["like", "ask", "start", "help", "open"],
  ["close", "stop", "miss", "love", "clean"],
  ["watch", "listen", "answer", "call", "walk"],
  ["talk", "look", "turn", "move", "change"],
  ["work", "live", "play", "want", "need"],
];

ENLAB.ui = {
  es: {
    tabs: { hoy: "Hoy", vocales: "Oír", verbos: "Verbos", quiz: "Juego", hablar: "Hablar", ia: "Ayuda" },
    kids: "Modo niño",
    uiLang: "English UI",
    repaso: "Solo repaso (10 min)",
    shadow: "Shadowing",
    streak: "Últimos 30 días",
    weakPrint: "Imprimir débiles",
    transfer: "Código para otro PC",
    interview: "Simulacro entrevista",
    voiceHist: "Mis grabaciones hoy",
    robot: "Robot",
    real: "Gente real",
    due: "Vence hoy",
    week: "Esta semana",
    dict: "Dictado",
    listen: "Escucha",
    role: "Role-play",
    class: "Modo aula",
    weekly: "Examen semanal",
    email: "Emails",
    travel: "Modo viaje",
    cert: "Examen certificado",
    podcast: "Mini-podcasts",
    chat: "Slack / Teams",
    duo: "Duo 2 jugadores",
    audit: "Auditoría A–R",
    situations: "Frases por situación",
    phrasals: "Phrasals de trabajo",
    repasoActive: "Modo repaso — solo débiles",
  },
  en: {
    tabs: { hoy: "Today", vocales: "Listen", verbos: "Verbs", quiz: "Play", hablar: "Speak", ia: "Help" },
    kids: "Kids mode",
    uiLang: "Interfaz en español",
    repaso: "Review only (10 min)",
    shadow: "Shadowing",
    streak: "Last 30 days",
    weakPrint: "Print weak list",
    transfer: "Code for another PC",
    interview: "Interview drill",
    voiceHist: "Today's recordings",
    robot: "Robot",
    real: "Real people",
    due: "Due today",
    week: "This week",
    dict: "Dictation",
    listen: "Listening",
    role: "Role-play",
    class: "Classroom",
    weekly: "Weekly exam",
    email: "Emails",
    travel: "Travel mode",
    cert: "Certificate exam",
    podcast: "Mini-podcasts",
    chat: "Slack / Teams",
    duo: "Duo (2 players)",
    audit: "Audit A–R",
    situations: "Situation phrases",
    phrasals: "Work phrasals",
    repasoActive: "Review mode — weak items only",
  },
};
