/* Explicaciones de vocales (se fusionan con ENLAB). */
ENLAB.vowelKey = [
  ["ii", "I larga (sonrisa, más larga que “sí”)", "see, me, eat"],
  ["i", "I corta y relajada (no es la i española)", "sit, big, been"],
  ["ei", "como “ey” de rey, en una sílaba", "name, say, make"],
  ["e", "E de pez, corta", "bed, said, went"],
  ["ä", "A abierta, entre A y E (sonríe)", "cat, bad, ran"],
  ["a", "A corta de garganta (cup)", "cut, come, done"],
  ["aa", "A larga, boca abierta", "father, hot"],
  ["o", "O abierta (thought)", "thought, bought, saw"],
  ["ou", "OH que desliza a U", "go, know, home"],
  ["u", "U corta (put)", "put, took, good"],
  ["uu", "U larga", "too, you, food"],
  ["ai", "AI de hay", "I, my, write"],
  ["au", "AU de aula", "now, found, out"],
  ["ə", "vocal floja (schwa)", "about, taken"],
];

ENLAB.vowelIntro = [
  "El español tiene 5 vocales. El inglés americano tiene unas 14–15. Por eso la misma letra A no suena igual en cat, name, car, call y about: la letra es un dibujo; el sonido lo deciden la sílaba, las letras vecinas y el acento de la palabra.",
  "No intentes “leer como se escribe”. Pregúntate, en este orden: ¿la vocal está atrapada entre consonantes? ¿hay una E muda al final? ¿hay dos vocales juntas? ¿viene una R? ¿la sílaba está átona (sin golpe)?",
];

ENLAB.decideSteps = [
  { q: "1. ¿La sílaba acaba en consonante (cat, hop, sit)?", a: "Casi siempre vocal CORTA: ä, e, i, aa, a. Escucha cap, pet, sit, hop, cut." },
  { q: "2. ¿Hay una E al final que no se pronuncia (cape, hope, bite)?", a: "Esa E es un interruptor: alarga la vocal del medio. cap→cape, hop→hope. La E no se dice." },
  { q: "3. ¿Hay dos vocales seguidas (rain, see, boat, out)?", a: "A menudo suena el NOMBRE de la primera (A=ei, E=ii, I=ai, O=ou). Hay trampas: said, head, you." },
  { q: "4. ¿La vocal va pegada a R (car, her, for, work)?", a: "La R se come la vocal y crea un sonido nuevo. her, bird y turn suenan casi igual (er)." },
  { q: "5. ¿La sílaba va sin golpe de voz (about, banana, problem)?", a: "Casi cualquier letra (a, e, i, o, u) se vuelve schwa [ə]: un sonido flojo, rápido, de compromiso. El español no hace esto." },
];

ENLAB.vowelRules = [
  {
    title: "Regla 1 — Sílaba cerrada vs abierta",
    body: "Cerrada: la vocal está atrapada (consonante–vocal–consonante). Suena CORTA. Abierta: la vocal termina la sílaba. Suena LARGA, casi como el nombre de la letra en el abecedario inglés (A=ei, E=ii, I=ai, O=ou, U=yuu).",
    listen: ["cat", "pet", "sit", "hop", "cut", "me", "go", "hi", "no"],
    note: "Compara cat (cerrada, ä) con me (abierta, ii). No es que la A “a veces sea E”: cambió el tipo de sílaba.",
  },
  {
    title: "Regla 2 — La E muda (magic E)",
    body: "Patrón: consonante + vocal + consonante + E. La E casi nunca se pronuncia. Su trabajo es alargar la vocal de en medio. Por eso hope no es “jope” y made no es “máde”.",
    pairs: [
      ["cap", "cape"], ["pet", "Pete"], ["kit", "kite"], ["hop", "hope"],
      ["cut", "cute"], ["not", "note"], ["bit", "bite"], ["mad", "made"],
    ],
    note: "Si quitas la E, vuelve la vocal corta. Si la pones, la vocal “dice su nombre”.",
  },
  {
    title: "Regla 3 — Dos vocales juntas",
    body: "Dicho popular: “when two vowels go walking, the first one does the talking”. La primera suele decir su nombre y la segunda calla. Sirve para empezar; el inglés tiene excepciones que hay que oír y memorizar.",
    teams: [
      ["ai / ay", "ei", "rain, day, wait", "said se dice [sed], no [seid]"],
      ["ee", "ii", "see, green, keep", "muy estable"],
      ["ea", "ii (a veces e o ei)", "eat, tea  /  head, bread  /  great", "tres sonidos posibles: hay que oír la palabra"],
      ["oa", "ou", "boat, road, coat", "broad es excepción"],
      ["oo", "uu o u", "food, too  /  book, good", "blood se dice [blad]"],
      ["ou", "au (y otros)", "out, house, found", "you [yuu], could [kud], country [kántri]"],
      ["ow", "au o ou", "now, how  /  know, show", "la escritura no te dice cuál: oye now vs know"],
      ["oi / oy", "oi", "oil, boy, join", "estable"],
    ],
    listen: ["rain", "said", "see", "eat", "head", "great", "boat", "food", "book", "out", "you", "now", "know"],
    note: "La más traicionera: ea. eat [iit], head [jed], great [greit]. Tres familias, misma escritura.",
  },
  {
    title: "Regla 4 — Vocal + R",
    body: "La R inglesa no vibra como la RR. Se coloca atrás y tira de la vocal. No leas car como “car” español ni her como “jer” con E clara.",
    teams: [
      ["ar", "aar", "car, far, start", "boca más abierta que en español"],
      ["or / ore", "or", "for, more, short", "parecido a “or” pero con R inglesa"],
      ["er / ir / ur", "er", "her, bird, turn, first", "los tres suenan casi IGUAL en sílaba tónica"],
      ["wor", "wer", "work, word, world", "work no es “guork”: es [werk]"],
      ["ear", "iir / er / ar", "hear / learn / heart", "otra escritura, tres sonidos: oye cada una"],
    ],
    listen: ["car", "for", "her", "bird", "turn", "work", "hear", "learn", "heart"],
    note: "Truco de oro: her = bird = turn. Si escribes ir o ur, el oído igual oye er.",
  },
  {
    title: "Regla 5 — El schwa [ə], la vocal más común",
    body: "En sílabas ÁTONAS (sin golpe), el inglés debilita la vocal. Da igual que esté escrita a, e, i, o o u: suena [ə], una E/A floja y cortísima. Un hispanohablante tiende a decir todas las vocales “completas” (ba-na-na) y suena robótico.",
    listen: ["about", "taken", "problem", "sofa", "America", "banana", "photograph", "photography"],
    note: "photograph vs photography: al mover el ACENTO, cambian las vocales. El acento manda; las átonas se comen.",
  },
  {
    title: "Regla 6 — Misma escritura, otro sonido",
    body: "A veces no cambia la letra: cambia la FUNCIÓN. Tienes que leer la frase, no la palabra suelta.",
    teams: [
      ["read", "[riid] presente", "[red] pasado / participio", "I read every day / I read it yesterday"],
      ["live", "[liv] vivir", "[laiv] en vivo", "I live here / a live demo"],
      ["use", "[yuuz] verbo", "[yuus] sustantivo", "I use Git / the use of Git"],
      ["wind", "[wind] viento", "[waind] enrollar", "the wind / wind the cable"],
      ["lead", "[liid] liderar", "[led] plomo; y el pasado de lead es led", "lead the team / led (pasado)"],
    ],
    listen: ["read", "live", "use", "wind", "lead"],
    note: "En el Lab, al pulsar read o live el sintetizador elige UNA de las dos. El contexto lo pones tú: “I read it yesterday” vs “I read every day”.",
  },
  {
    title: "Regla 7 — Terminaciones -ed y -s",
    body: "No es capricho ni “a veces se come la e”. El oído sigue el último SONIDO de la raíz, no la última letra.",
    teams: [
      ["-ed = [t]", "raíz sorda: p k f s sh ch th", "liked, stopped, watched, missed", "liked suena [laikt], no [láiked]"],
      ["-ed = [d]", "raíz sonora o vocal", "played, called, loved, cleaned", "una sola sílaba extra no: se pega la D"],
      ["-ed = [id]", "la raíz termina en T o D", "wanted, needed, decided", "aquí SÍ hay sílaba extra"],
      ["-s = [s]", "sorda", "likes, stops, writes", ""],
      ["-s = [z]", "sonora o vocal", "goes, reads, lives, plays", "goes es [góuz]"],
      ["-s = [iz]", "s, z, sh, ch, x, ge", "watches, misses, changes", "sílaba extra"],
    ],
    listen: ["liked", "played", "wanted", "goes", "likes", "watches"],
    note: "wanted tiene tres sílabas porque acaba en T. liked no añade sílaba.",
  },
];

ENLAB.letterNotes = {
  A: "Cinco destinos habituales: ä (cat, sílaba cerrada), ei (name, E muda o ai/ay), aar (car), o (call, saw), ə (about, átona). Excepciones de memoria: any, many, said, says → suenan con E.",
  E: "Cerrada = e (bed, went). Abierta / ee / ea = ii (me, see, eat). Átona = ə (taken). Al final, muchas veces muda (make). the átona es [dhə]; the tónica delante de vocal es [dhii apple].",
  I: "Cerrada = i corta (sit, this, give, live=vivir). E muda / igh = ai (like, time, night, write). Excepción frecuente: live [liv] vs live [laiv]. machine y police tienen ii (préstamos).",
  O: "Cerrada en americano ≈ aa (hot, got, not), no la O española. Abierta / oa / E muda = ou (go, home, hope). Excepciones gravadas a fuego: come, some, done, love, does, nothing suenan con a (cup). do, to, who, move suenan uu.",
  U: "Cerrada = a (cut, but, run). E muda / use = yuu (cute, music). Después de r, l, j a veces uu (blue, rule, June). Grupo corto: put, push, full, could, would, book (u de put, no cut).",
  Y: "Al inicio es consonante (yes, you). Al final de palabra corta = ai (my, by, fly). Al final de palabra larga = i (happy, city). En el medio a veces i (gym, system).",
};

ENLAB.letterExtra = {
  Y: {
    letter: "Y",
    sounds: [
      { ipa: "ai", when: "Final de 1 sílaba / tónica", examples: ["my", "by", "fly", "type"] },
      { ipa: "i", when: "Final de palabra larga o en el medio", examples: ["happy", "city", "gym", "system"] },
      { ipa: "y", when: "Consonante al inicio", examples: ["yes", "you", "year"] },
    ],
  },
};

/* Pares extra para el quiz de oído (ortografía distinta; el sintetizador sí puede contrastarlos). */
ENLAB.earPairs = [
  { a: "cap", b: "cape", pa: "käp", pb: "keip", why: "E muda: ä vs ei" },
  { a: "hat", b: "hate", pa: "hät", pb: "heit", why: "E muda" },
  { a: "plan", b: "plane", pa: "plän", pb: "plein", why: "E muda" },
  { a: "tap", b: "tape", pa: "täp", pb: "teip", why: "E muda" },
  { a: "pet", b: "Pete", pa: "pet", pb: "piit", why: "e corta vs ii" },
  { a: "hop", b: "hope", pa: "jaap", pb: "jóup", why: "E muda: aa vs ou" },
  { a: "not", b: "note", pa: "naat", pb: "nóut", why: "E muda" },
  { a: "rob", b: "robe", pa: "raab", pb: "róub", why: "E muda" },
  { a: "cut", b: "cute", pa: "kat", pb: "kyuut", why: "E muda: a vs yuu" },
  { a: "bit", b: "bite", pa: "bit", pb: "bait", why: "i corta vs ai" },
  { a: "hid", b: "hide", pa: "jid", pb: "jaid", why: "E muda" },
  { a: "kit", b: "kite", pa: "kit", pb: "kait", why: "E muda" },
  { a: "fill", b: "file", pa: "fil", pb: "fail", why: "i vs ai" },
  { a: "ship", b: "sheep", pa: "ship", pb: "shiip", why: "i corta vs ii larga (el par más útil)" },
  { a: "sit", b: "seat", pa: "sit", pb: "siit", why: "i vs ii" },
  { a: "it", b: "eat", pa: "it", pb: "iit", why: "i vs ii" },
  { a: "this", b: "these", pa: "dhis", pb: "dhiiz", why: "i vs ii + TH" },
  { a: "chip", b: "cheap", pa: "chip", pb: "chiip", why: "i vs ii" },
  { a: "full", b: "fool", pa: "ful", pb: "fuul", why: "u corta vs uu" },
  { a: "pull", b: "pool", pa: "pul", pb: "puul", why: "u vs uu" },
  { a: "leave", b: "live", pa: "liiv", pb: "liv", why: "ii vs i (live = vivir)" },
  { a: "walk", b: "work", pa: "wok", pb: "werk", why: "o vs er" },
  { a: "now", b: "know", pa: "nau", pb: "nóu", why: "au vs ou (know: K muda)" },
  { a: "come", b: "comb", pa: "kam", pb: "koum", why: "a (excepción) vs ou" },
  { a: "done", b: "do", pa: "dan", pb: "duu", why: "a vs uu" },
  { a: "said", b: "sad", pa: "sed", pb: "säd", why: "said es E, no ei" },
  { a: "men", b: "man", pa: "men", pb: "män", why: "e vs ä" },
  { a: "bed", b: "bad", pa: "bed", pb: "bäd", why: "e vs ä" },
  { a: "pen", b: "pan", pa: "pen", pb: "pän", why: "e vs ä" },
  { a: "coat", b: "caught", pa: "kout", pb: "kot", why: "ou vs o" },
  { a: "very", b: "berry", pa: "veri", pb: "beri", why: "V vs B (dientes vs labios)", min: 3 },
  { a: "vote", b: "boat", pa: "vout", pb: "bout", why: "V vs B", min: 3 },
  { a: "think", b: "sink", pa: "think", pb: "sink", why: "TH vs S", min: 3 },
  { a: "I can go", b: "I can't go", pa: "kən", pb: "känt", why: "can átono vs can't", min: 3 },
  { a: "car", b: "card", pa: "kaar", pb: "kaart", why: "no te comas la D final", min: 3 },
  { a: "ship", b: "chip", pa: "ship", pb: "chip", why: "SH vs CH", min: 4 },
  { a: "chip", b: "jeep", pa: "chip", pb: "jiip", why: "CH vs J", min: 4 },
  { a: "wine", b: "vine", pa: "wain", pb: "vain", why: "W vs V", min: 4 },
  { a: "I live here", b: "a live concert", pa: "liv", pb: "laiv", why: "live: verbo vs adjetivo", min: 2 },
  { a: "I use this", b: "the use of this", pa: "yuuz", pb: "yuus", why: "use: verbo vs sustantivo", min: 2 },
  { a: "Please close the door", b: "The store is close", pa: "klouz", pb: "klous", why: "close: verbo vs adjetivo", min: 2 },
  { a: "I read every day", b: "I read it yesterday", pa: "riid", pb: "red", why: "read: presente vs pasado", min: 2 },
  { a: "I will record it", b: "an old record", pa: "reCORD", pb: "REcord", why: "record: verbo vs sustantivo", min: 3 },
  { a: "thirteen", b: "thirty", pa: "thir-TEEN", pb: "THIR-ty", why: "13 vs 30: el golpe se mueve", min: 3 },
  { a: "woman", b: "women", pa: "wúmən", pb: "wímin", why: "una vs varias (no se lee como se escribe)", min: 3 },
  { a: "thought", b: "taught", pa: "thot", pb: "tot", why: "TH vs T (pensé vs enseñé)", min: 3 },
  { a: "bag", b: "back", pa: "bag", pb: "bak", why: "G con voz vs K sorda", min: 3 },
  { a: "sing", b: "sin", pa: "sing", pb: "sin", why: "NG vs N", min: 4 },
  { a: "zoo", b: "sue", pa: "zuu", pb: "suu", why: "Z vs S", min: 4 },
  { a: "yes", b: "Jess", pa: "yes", pb: "jes", why: "Y vs J", min: 4 },
];

ENLAB.starter40 = [
  "be", "have", "do", "go", "get", "make", "take", "give", "see", "know",
  "think", "say", "tell", "come", "become", "begin", "leave", "keep", "lead", "write",
  "read", "speak", "understand", "build", "find", "show", "choose", "run", "set", "put",
  "send", "meet", "pay", "lose", "catch", "teach", "bring", "grow", "hold", "win",
];

/* Misma escritura, otro rol. Oír SIEMPRE la frase: suelta el sintetizador elige una sola. */
ENLAB.wordRoles = [
  {
    word: "live",
    min: 2,
    change: "Cambia el sonido (i corta vs AI)",
    roles: [
      { pos: "verbo", pron: "liv", en: "I live in Ecuador.", es: "Vivo en Ecuador." },
      { pos: "adjetivo", pron: "laiv", en: "This is a live concert.", es: "Este es un concierto en vivo." },
    ],
  },
  {
    word: "use",
    min: 2,
    change: "Verbo sonoro [yuuz]; sustantivo sordo [yuus]",
    roles: [
      { pos: "verbo", pron: "yuuz", en: "I use this every day.", es: "Uso esto todos los días." },
      { pos: "sustantivo", pron: "yuus", en: "What is the use of this?", es: "¿De qué sirve esto?" },
    ],
  },
  {
    word: "read",
    min: 2,
    change: "Mismo escrito; presente y pasado suenan distinto",
    roles: [
      { pos: "presente", pron: "riid", en: "I read every morning.", es: "Leo cada mañana." },
      { pos: "pasado", pron: "red", en: "I read it yesterday.", es: "Lo leí ayer." },
    ],
  },
  {
    word: "close",
    min: 2,
    change: "Verbo [klouz] con Z; adjetivo [klous] con S",
    roles: [
      { pos: "verbo", pron: "klouz", en: "Please close the door.", es: "Por favor cierra la puerta." },
      { pos: "adjetivo", pron: "klous", en: "The store is close.", es: "La tienda está cerca." },
    ],
  },
  {
    word: "record",
    min: 3,
    change: "Sustantivo: golpe al INICIO. Verbo: golpe al FINAL.",
    roles: [
      { pos: "sustantivo", pron: "RÉ-cord", en: "I bought an old record.", es: "Compré un disco viejo." },
      { pos: "verbo", pron: "re-CÓRD", en: "I will record the meeting.", es: "Voy a grabar la reunión." },
    ],
  },
  {
    word: "present",
    min: 3,
    change: "Sustantivo PRE-sent; verbo pre-SENT",
    roles: [
      { pos: "sustantivo", pron: "PRÉ-sent", en: "I have a present for you.", es: "Tengo un regalo para ti." },
      { pos: "verbo", pron: "pre-SÉNT", en: "They present the award tonight.", es: "Presentan el premio esta noche." },
      { pos: "adjetivo", pron: "PRÉ-sent", en: "Is everyone present?", es: "¿Están todos presentes?" },
    ],
  },
  {
    word: "project",
    min: 3,
    change: "PRO-ject = el proyecto. pro-JECT = proyectar",
    roles: [
      { pos: "sustantivo", pron: "PRÓ-ject", en: "This project is important.", es: "Este proyecto es importante." },
      { pos: "verbo", pron: "pro-YÉCT", en: "They project the results.", es: "Proyectan los resultados." },
    ],
  },
  {
    word: "object",
    min: 3,
    change: "ÓB-ject = cosa. ob-JÉCT = objetar",
    roles: [
      { pos: "sustantivo", pron: "ÓB-ject", en: "What is that object?", es: "¿Qué es ese objeto?" },
      { pos: "verbo", pron: "ob-YÉCT", en: "I object to that idea.", es: "Me opongo a esa idea." },
    ],
  },
  {
    word: "increase",
    min: 3,
    change: "IN-crease nombre; in-CREASE verbo. Muy frecuente en trabajo.",
    roles: [
      { pos: "sustantivo", pron: "ÍN-crease", en: "There was an increase in price.", es: "Hubo un aumento de precio." },
      { pos: "verbo", pron: "in-CRÍS", en: "They will increase the price.", es: "Van a aumentar el precio." },
    ],
  },
  {
    word: "content",
    min: 3,
    change: "CÓN-tent = contenido. con-TÉNT = estar a gusto",
    roles: [
      { pos: "sustantivo", pron: "CÓN-tent", en: "I read the content of the email.", es: "Leí el contenido del correo." },
      { pos: "adjetivo", pron: "con-TÉNT", en: "I am content with that.", es: "Estoy conforme con eso." },
    ],
  },
  {
    word: "permit",
    min: 3,
    change: "PÉR-mit permiso; per-MÍT permitir",
    roles: [
      { pos: "sustantivo", pron: "PÉR-mit", en: "Do you have a permit?", es: "¿Tienes un permiso?" },
      { pos: "verbo", pron: "per-MÍT", en: "They permit it.", es: "Lo permiten." },
    ],
  },
  {
    word: "wind",
    min: 3,
    change: "El viento [wind] vs enrollar [waind]",
    roles: [
      { pos: "sustantivo", pron: "wind", en: "The wind is strong today.", es: "El viento está fuerte hoy." },
      { pos: "verbo", pron: "waind", en: "Wind the cable, please.", es: "Enrolla el cable, por favor." },
    ],
  },
  {
    word: "perfect",
    min: 4,
    change: "Adjetivo PÉR-fect; verbo per-FÉCT (pulir)",
    roles: [
      { pos: "adjetivo", pron: "PÉR-fect", en: "That is a perfect answer.", es: "Esa es una respuesta perfecta." },
      { pos: "verbo", pron: "per-FÉCT", en: "I want to perfect my English.", es: "Quiero perfeccionar mi inglés." },
    ],
  },
  {
    word: "separate",
    min: 4,
    change: "Adjetivo acaba flojo [sepərit]; verbo [sepəreit]",
    roles: [
      { pos: "adjetivo", pron: "SÉ-pə-rit", en: "They have separate rooms.", es: "Tienen habitaciones separadas." },
      { pos: "verbo", pron: "SÉ-pə-reit", en: "Please separate the files.", es: "Por favor separa los archivos." },
    ],
  },
  {
    word: "estimate",
    min: 4,
    change: "Nombre [éstimit]; verbo [éstimeit]",
    roles: [
      { pos: "sustantivo", pron: "ÉS-ti-mit", en: "Give me an estimate.", es: "Dame un presupuesto." },
      { pos: "verbo", pron: "ÉS-ti-meit", en: "We estimate two weeks.", es: "Estimamos dos semanas." },
    ],
  },
  {
    word: "graduate",
    min: 4,
    change: "Persona [gráyuit]; verbo [gráyueit]",
    roles: [
      { pos: "sustantivo", pron: "GRÁ-yu-it", en: "She is a graduate.", es: "Ella es licenciada / egresada." },
      { pos: "verbo", pron: "GRÁ-yu-eit", en: "She will graduate in June.", es: "Se gradúa en junio." },
    ],
  },
  {
    word: "excuse",
    min: 4,
    change: "Sustantivo sordo [yuus]; verbo [yuuz]",
    roles: [
      { pos: "sustantivo", pron: "ex-KYÚUS", en: "That is a bad excuse.", es: "Esa es una mala excusa." },
      { pos: "verbo", pron: "ex-KYÚUZ", en: "Excuse me.", es: "Perdón / con permiso." },
    ],
  },
  {
    word: "address",
    min: 4,
    change: "A-dress = dirección. a-DRÉSS = dirigirse a alguien",
    roles: [
      { pos: "sustantivo", pron: "Á-dress", en: "What is your address?", es: "¿Cuál es tu dirección?" },
      { pos: "verbo", pron: "a-DRÉSS", en: "She will address the team.", es: "Ella se dirigirá al equipo." },
    ],
  },
  {
    word: "tear",
    min: 3,
    change: "Lágrima [tiir] vs romper [teer]",
    roles: [
      { pos: "sustantivo", pron: "tiir", en: "A tear ran down her face.", es: "Se le cayó una lágrima." },
      { pos: "verbo", pron: "teer", en: "Don't tear the paper.", es: "No rompas el papel." },
    ],
  },
  {
    word: "wound",
    min: 4,
    change: "Herida [wuund] vs pasado de wind [waund]",
    roles: [
      { pos: "sustantivo", pron: "wuund", en: "The wound is healing.", es: "La herida está sanando." },
      { pos: "verbo", pron: "waund", en: "She wound the cable.", es: "Ella enrolló el cable. (pasado de wind)" },
    ],
  },
];

/* Letras escritas que no suenan, o sílabas enteras que se comen. */
ENLAB.dropLetters = [
  {
    min: 2,
    title: "E muda — como en sometimes",
    body: "sometimes NO es so-me-ti-mes. Son dos golpes: SÁM-taimz. En some, la E no es una sílaba (suena [sam], o de cup). En times, la E es el interruptor mágico: no se dice y convierte i en AI + S como Z. Igual: make, time, like, give es excepción ([giv], E muda igualmente).",
    items: [
      { word: "sometimes", note: "sám-taimz (2 sílabas)", skip: "E de some + E de times" },
      { word: "time", note: "taim", skip: "E" },
      { word: "make", note: "meik", skip: "E" },
      { word: "like", note: "laik", skip: "E" },
      { word: "people", note: "píi-pəl", skip: "o" },
      { word: "give", note: "giv (excepción: I corta)", skip: "E" },
    ],
  },
  {
    min: 2,
    title: "Se come una sílaba entera",
    body: "El español quiere cada vocal. El inglés aplasta la del medio. every ≈ ÉV-ri (no é-ve-ri). interesting ≈ ÍN-tris-ting. Si deletreas al hablar, suenas a libro.",
    items: [
      { word: "every", note: "év-ri", skip: "e del medio" },
      { word: "evening", note: "íiv-ning", skip: "e del medio" },
      { word: "family", note: "fám-li", skip: "i del medio" },
      { word: "camera", note: "kám-rə", skip: "e del medio" },
      { word: "business", note: "bíz-nis", skip: "i" },
      { word: "different", note: "díf-rənt", skip: "e del medio" },
      { word: "interesting", note: "ín-tris-ting", skip: "e extra" },
      { word: "comfortable", note: "cómf-tər-bəl", skip: "or-ta" },
      { word: "chocolate", note: "chóc-lit", skip: "o del medio" },
      { word: "vegetable", note: "véj-tə-bəl", skip: "eta" },
      { word: "favorite", note: "féiv-rit", skip: "o" },
      { word: "probably", note: "práb-li", skip: "a/o del medio" },
    ],
  },
  {
    min: 2,
    title: "K, W, GH: se escriben y callan",
    body: "kn-, wr-, y -igh / -ough a menudo. No es capricho: patrones. know, write, night, though.",
    items: [
      { word: "know", note: "nóu", skip: "K" },
      { word: "knife", note: "naif", skip: "K" },
      { word: "write", note: "rait", skip: "W (+ E)" },
      { word: "wrong", note: "rong", skip: "W" },
      { word: "two", note: "tuu", skip: "W" },
      { word: "answer", note: "án-sər", skip: "W" },
      { word: "night", note: "nait", skip: "GH" },
      { word: "though", note: "dhóu", skip: "GH (y ough raro)" },
      { word: "high", note: "jai", skip: "GH" },
      { word: "eight", note: "eit", skip: "GH" },
    ],
  },
  {
    min: 2,
    title: "L, T, B, D mudas",
    body: "could / would / should: la L no se oye. listen y often: T a menudo desaparece. lamb, thumb: B final muda. Wednesday se come casi todo el medio.",
    items: [
      { word: "could", note: "kud", skip: "L" },
      { word: "would", note: "wud", skip: "L" },
      { word: "should", note: "shud", skip: "L" },
      { word: "talk", note: "tok", skip: "L" },
      { word: "walk", note: "wok", skip: "L" },
      { word: "half", note: "haf", skip: "L" },
      { word: "listen", note: "lís-ən", skip: "T" },
      { word: "often", note: "ó-fən (T opcional)", skip: "T (muchas veces)" },
      { word: "castle", note: "ká-səl", skip: "T" },
      { word: "Christmas", note: "krís-məs", skip: "T" },
      { word: "lamb", note: "lam", skip: "B" },
      { word: "thumb", note: "tham", skip: "B" },
      { word: "climb", note: "klaim", skip: "B" },
      { word: "doubt", note: "daut", skip: "B" },
      { word: "Wednesday", note: "wénz-dei", skip: "d + e del medio" },
      { word: "handsome", note: "han-səm", skip: "D" },
    ],
  },
  {
    min: 3,
    title: "H, P, U, C, N que no suenan",
    body: "hour y honest: H muda (al revés de house). psychology, receipt: P muda. guitar, guess, build: U extra. muscle, scissors: C extra. autumn, column: N final muda.",
    items: [
      { word: "hour", note: "áu-ər", skip: "H" },
      { word: "honest", note: "á-nist", skip: "H" },
      { word: "honor", note: "á-nər", skip: "H" },
      { word: "island", note: "ái-lənd", skip: "S" },
      { word: "receipt", note: "ri-síit", skip: "P" },
      { word: "psychology", note: "sai-có-lə-yi", skip: "P" },
      { word: "cupboard", note: "cáb-ərd", skip: "P" },
      { word: "guitar", note: "gi-táar", skip: "U" },
      { word: "guess", note: "ges", skip: "U" },
      { word: "build", note: "bild", skip: "U" },
      { word: "muscle", note: "má-səl", skip: "C" },
      { word: "scissors", note: "sí-zərz", skip: "C" },
      { word: "autumn", note: "ó-təm", skip: "N" },
      { word: "column", note: "có-ləm", skip: "N" },
      { word: "sign", note: "sain", skip: "G" },
      { word: "foreign", note: "fór-ən", skip: "G + ei raro" },
    ],
  },
  {
    min: 4,
    title: "Las raras (B2, de memoria)",
    body: "No hay regla bonita. Se memorizan con audio: colonel, queue, February, restaurant, temperature, naturally.",
    items: [
      { word: "colonel", note: "kér-nəl", skip: "casi todo se deforma" },
      { word: "queue", note: "kyuu", skip: "ueue" },
      { word: "February", note: "féb-ru-eri / féb-yoo-", skip: "a veces la 1.ª r" },
      { word: "restaurant", note: "rés-trənt", skip: "au del medio" },
      { word: "temperature", note: "tém-prə-chər", skip: "e extra" },
      { word: "naturally", note: "nách-rə-li", skip: "u-ra" },
      { word: "usually", note: "yúu-zhə-li", skip: "al del medio" },
      { word: "actually", note: "ák-chə-li", skip: "ua" },
      { word: "basically", note: "béi-sik-li", skip: "al" },
      { word: "sword", note: "sord", skip: "W" },
    ],
  },
];

ENLAB.tailTalk = [
  {
    min: 2,
    title: "-tion / -sion = “shən” (no “ción”)",
    body: "Nación en español termina en -ción clara. En inglés nation ≈ NÉI-shən: TI suena SH y la última vocal es schwa floja. information, decision, television. No digas “ná-tion” ni “informa-ción”.",
    items: [
      { word: "nation", note: "néi-shən" },
      { word: "information", note: "in-fər-MÉI-shən" },
      { word: "question", note: "kwés-chən (ch, no sh)" },
      { word: "decision", note: "di-sí-zhən (ZH suave)" },
      { word: "television", note: "té-lə-vi-zhən" },
      { word: "attention", note: "ə-TÉN-shən" },
    ],
  },
  {
    min: 2,
    title: "-ture, -ous, -able",
    body: "picture ≈ PÍK-chər (CH, no “tur”). famous ≈ FÉI-məs (no “feimous” con OU). comfortable ya lo viste: se come sílabas. nature, future, nervous, serious.",
    items: [
      { word: "picture", note: "pík-chər" },
      { word: "nature", note: "néi-chər" },
      { word: "future", note: "fyúu-chər" },
      { word: "famous", note: "féi-məs" },
      { word: "nervous", note: "nér-vəs" },
      { word: "serious", note: "sír-i-əs" },
      { word: "possible", note: "pó-sə-bəl" },
      { word: "comfortable", note: "cómf-tər-bəl" },
    ],
  },
  {
    min: 2,
    title: "C, G y CH: la letra miente",
    body: "C = K delante de a/o/u (cat, come) y S delante de e/i/y (city, ice). ocean es SH. G = gato en go/got; J suave en general, giant. Excepciones: get, give, girl (G dura). CH = cheap; en school es K; en chef/machine es SH.",
    items: [
      { word: "cat", note: "K" },
      { word: "city", note: "S" },
      { word: "ice", note: "S" },
      { word: "ocean", note: "óu-shən (SH)" },
      { word: "go", note: "G dura" },
      { word: "general", note: "J suave" },
      { word: "get", note: "G dura (excepción)" },
      { word: "give", note: "G dura (excepción)" },
      { word: "cheap", note: "CH de 'ch'" },
      { word: "school", note: "K" },
      { word: "chef", note: "SH" },
      { word: "machine", note: "mə-SHÍIN" },
    ],
  },
  {
    min: 3,
    title: "Phrasal: el golpe va en la partícula",
    body: "turn it OFF, look it UP, find OUT, give UP, put it ON. Lo importante es OFF/UP/OUT, no el verbo. Si golpeas solo TURN, no se entiende. En el nombre suele ser al revés: a PICK-up, a CHECK-in.",
    items: [
      { word: "Turn it off.", note: "OFF" },
      { word: "Look it up.", note: "UP" },
      { word: "Find out.", note: "OUT" },
      { word: "Give up.", note: "UP" },
      { word: "Put it on.", note: "ON" },
      { word: "Pick it up.", note: "verbo + UP" },
      { word: "a pickup", note: "nombre: PICK-up" },
      { word: "Check in.", note: "verbo" },
      { word: "a check-in", note: "nombre: CHECK-in" },
    ],
  },
  {
    min: 3,
    title: "Compuesto vs dos palabras",
    body: "GREENhouse = invernadero (un concepto, golpe al inicio). green HOUSE = una casa verde (golpe en HOUSE). WHITE House (la de EE.UU.) vs a white house. El golpe dice si es “una cosa” o “adjetivo + cosa”.",
    items: [
      { word: "greenhouse", note: "GREEN-house (invernadero)" },
      { word: "a green house", note: "casa verde" },
      { word: "the White House", note: "la Casa Blanca" },
      { word: "a white house", note: "una casa blanca" },
      { word: "blackboard", note: "BLACK-board (pizarra)" },
      { word: "a black board", note: "un tablero negro" },
      { word: "hot dog", note: "HOT dog" },
      { word: "ice cream", note: "ICE cream" },
    ],
  },
  {
    min: 3,
    title: "Años, cero y dinero (oír, no adivinar)",
    body: "1999 = nineteen ninety-nine. 2005 = two thousand five o twenty oh five. 2015 = twenty fifteen. El 0 del teléfono es oh, no always “zero”. $5.50 = five fifty. Y 13/30: el golpe se mueve (ya en Tips).",
    items: [
      { word: "nineteen ninety-nine", note: "1999" },
      { word: "two thousand five", note: "2005" },
      { word: "twenty fifteen", note: "2015" },
      { word: "oh five", note: "05 en teléfono" },
      { word: "five fifty", note: "$5.50" },
      { word: "thirteen", note: "thir-TEEN" },
      { word: "thirty", note: "THIR-ty" },
      { word: "oh", note: "0" },
    ],
  },
  {
    min: 4,
    title: "L oscura (feel, milk, people)",
    body: "Al final o antes de consonante, la L inglesa se “engorda” atrás: feel, milk, people, full. No es la L clara de “luna”. leaf (inicio, L clara) vs feel (final, L oscura).",
    items: [
      { word: "leaf", note: "L clara al inicio" },
      { word: "feel", note: "L oscura al final" },
      { word: "milk", note: "L oscura" },
      { word: "people", note: "pía-pəl" },
      { word: "full", note: "ful" },
      { word: "call", note: "kol" },
    ],
  },
];
