/* Niveles CEFR: una ruta A1→B2. La meta recomendada es B1. */
ENLAB.verbsA1 = [
  "be", "have", "do", "go", "get", "make", "take", "see", "say", "come",
  "give", "know", "think", "find", "leave",
];

ENLAB.cefr = {
  a1: {
    num: 1,
    name: "A1",
    title: "Principiante",
    short: "Fácil",
    goal: "Sonidos que el español no tiene y los 15 verbos más usados. Frases cortas.",
    next: "Cuando cap/cape y go/went/gone te salgan sin dudar, pasa a A2.",
  },
  a2: {
    num: 2,
    name: "A2",
    title: "Básico",
    short: "Base",
    goal: "E muda, dos vocales, -ed/-s, contracciones, 40 verbos. I went / I have gone.",
    next: "Cuando escuches la diferencia ship/sheep y uses I've, pasa a B1.",
  },
  b1: {
    num: 3,
    name: "B1",
    title: "Intermedio (meta)",
    short: "Meta",
    goal: "Schwa, acento de palabra, R, ough, present perfect, ritmo básico. Aquí ya puedes defender una conversación.",
    next: "Si te entienden siempre pero suenas “español con palabras en inglés”, prueba B2. En Oído abre Tips B1/B2.",
  },
  b2: {
    num: 4,
    name: "B2",
    title: "Intermedio alto",
    short: "Reto",
    goal: "Los 193 verbos como diccionario, unir palabras, formas débiles, intonación. Más natural, no obligatorio para ser B1.",
    next: "Sigue con oído real (series, YouGlish) y repetición en voz alta. Los tips B2 son flap T, gonna y unir palabras.",
  },
};

ENLAB.vowelRules.forEach((r, i) => { r.min = [1, 1, 2, 3, 3, 3, 2][i]; });
ENLAB.decideSteps.forEach((s, i) => { s.min = [1, 1, 2, 3, 3][i]; });

ENLAB.phrasesA1 = [
  { en: "I go to work every day.", es: "Voy al trabajo todos los días." },
  { en: "I have a question.", es: "Tengo una pregunta." },
  { en: "I did it yesterday.", es: "Lo hice ayer." },
  { en: "Can you help me?", es: "¿Puedes ayudarme?" },
  { en: "I don't know.", es: "No sé." },
  { en: "See you tomorrow.", es: "Nos vemos mañana." },
];

ENLAB.rhythm = [
  {
    min: 3,
    title: "El español y el inglés no “cantan” igual",
    body: "En español casi cada sílaba tiene el mismo golpe (te-le-fo-no). En inglés el golpe va a las palabras IMPORTANTES (nombres, verbos, adjetivos) y las chicas (to, of, a, can, the) se aplastan. Si das el mismo golpe a todas, suenas robótico aunque cada palabra esté “bien”.",
    listen: ["I want to go to the store", "I HAVE to GO to the STORE"],
  },
  {
    min: 3,
    title: "Palabras débiles (to, of, for, can, a, the)",
    body: "Átonas suenan [ə] o se comen. to ≈ [tə], of ≈ [əv], can (puedo) ≈ [kən] — can (lata) es [kän]. the: [dhə] antes de consonante, [dhii] antes de vocal.",
    listen: ["to", "of", "can", "the apple", "the book", "I can do it"],
  },
  {
    min: 4,
    title: "Unir palabras (linking)",
    body: "Si una acaba en consonante y la siguiente empieza por vocal, se pegan: an apple ≈ a-napple. want to ≈ wanna (informal). did you ≈ didja. No es “mal inglés”: es cómo se habla.",
    listen: ["an apple", "come on", "pick it up", "want to", "did you"],
  },
  {
    min: 4,
    title: "Entonación",
    body: "Pregunta de sí/no (Are you ready?) suele subir al final. Pregunta con What/Where/Why suele bajar. En español muchas preguntas también suben: no copies el mismo canto a todas las frases en inglés.",
    listen: ["Are you ready?", "What do you do?", "I live in Ecuador."],
  },
];

ENLAB.phrasesB1 = [
  { en: "I went there yesterday.", es: "Fui ayer. (momento concreto → pasado simple)" },
  { en: "I have already done it.", es: "Ya lo he hecho. (experiencia / resultado ahora)" },
  { en: "I've been busy today.", es: "He estado ocupado hoy. been ≈ [bin]" },
  { en: "I thought so.", es: "Ya me lo imaginaba. thought = [thot]" },
  { en: "I can't hear you.", es: "No te oigo. can't se oye larga + T" },
  { en: "Can I ask you something?", es: "¿Puedo preguntarte algo? can átono ≈ [kən]" },
  { en: "I've never tried that.", es: "Nunca lo he probado." },
  { en: "That sounds good.", es: "Suena bien." },
  { en: "It depends.", es: "Depende." },
  { en: "I'm not sure yet.", es: "Aún no estoy seguro." },
  { en: "See what I mean?", es: "¿Me entiendes?" },
  { en: "I didn't get it.", es: "No lo entendí / no lo conseguí." },
];

ENLAB.phrasesB2 = [
  { en: "I've been meaning to tell you.", es: "Tenía pensado decírtelo. (present perfect continuo)" },
  { en: "That's what I thought.", es: "Eso es lo que pensé." },
  { en: "I should've asked first.", es: "Debí haber preguntado antes. should've ≈ [shúdəv]" },
  { en: "We're gonna have to wait.", es: "Vamos a tener que esperar. gonna = informal" },
  { en: "I used to live there.", es: "Antes vivía ahí. used to ≈ [yúustə]" },
  { en: "As far as I know.", es: "Por lo que sé." },
  { en: "I see what you mean.", es: "Entiendo lo que dices." },
  { en: "It's kind of complicated.", es: "Es un poco complicado. kind of ≈ [káində]" },
  { en: "I would have done the same.", es: "Hubiera hecho lo mismo. would've ≈ [wúdəv]" },
  { en: "Let's get it over with.", es: "Terminemos de una vez." },
];

ENLAB.bTips = [
  {
    min: 3,
    tag: "B1 · trampa 1",
    title: "B y V no son la misma letra",
    body: "En español casi siempre suenan igual. En inglés very no es berry: V = dientes en el labio de abajo (como F, pero con voz). B = los dos labios. Si dices have con B, oyes jab. Practica: very, have, live, vote.",
    listen: ["very", "berry", "have", "vote", "boat", "live"],
    yg: "very",
  },
  {
    min: 3,
    tag: "B1 · trampa 2",
    title: "TH: tres errores distintos",
    body: "think no es sink (S) ni fink (F). this no es dis. Lengua entre los dientes + aire. Sorda: think, thought, with (a veces). Sonora, con voz: this, the, they. Es el sonido que más te delata; 2 minutos al día bastan.",
    listen: ["think", "sink", "this", "the", "they", "thought"],
    yg: "think",
  },
  {
    min: 3,
    tag: "B1 · listening",
    title: "can vs can't: el par que más se falla",
    body: "En la frase, can (puedo) se aplasta: I can go ≈ [ai kən góu]. can't se queda fuerte y se oye la T: I can't go ≈ [ai känt góu]. Aisladas, can se pronuncia fuerte [kän] y se parece a can't: por eso siempre óyelas en frase, no sueltas.",
    listen: ["I can go", "I can't go", "Can I help?", "I can't hear you"],
    yg: "I can't",
  },
  {
    min: 3,
    tag: "B1 · finales",
    title: "No te comas la última consonante",
    body: "card no es car. walked no es walk. things no es thing. El español a veces suaviza el final; el inglés necesita esa T, D, S, K. Si te comen la palabra, casi siempre faltó el cierre.",
    listen: ["car", "card", "walk", "walked", "thing", "things", "have", "had"],
    yg: "walked",
  },
  {
    min: 3,
    tag: "B1 · verbos",
    title: "I went ≠ I have gone (cuándo)",
    body: "I went yesterday = momento cerrado, con ayer / en 2019 / cuando era niño. I have gone / I have already done it = conectado con ahora (experiencia o resultado). En entrevistas y charla: I've worked with Java está bien; I worked there in 2020 también. No mezcles yesterday con have.",
    listen: ["I went yesterday", "I have already done it", "I've never tried that", "I lived there in 2020"],
  },
  {
    min: 3,
    tag: "B1 · americano",
    title: "been se dice casi “bin”",
    body: "I have been ≈ I've bin. No “bin” de basura: una i corta relajada [bin], no [biin]. Lo mismo: pretty ≈ [príri], because a menudo [bikəz] o [kuz]. El B1 oficial no exige esto, pero el oído real sí.",
    listen: ["I've been busy", "I have been there", "pretty", "because"],
    yg: "I've been",
  },
  {
    min: 3,
    tag: "B1 · trampa 3",
    title: "school, no “eschool”",
    body: "En español: escuela, España, especial. En inglés no hay E delante: school, Spain, street, speak, stop, slow. Empieza con S larga: sss-kool. Si pones E, suenas a español aunque el resto esté bien.",
    listen: ["school", "Spain", "street", "speak", "stop", "slow", "special"],
    yg: "school",
  },
  {
    min: 3,
    tag: "B1 · H",
    title: "H se sopla (no es la J de José)",
    body: "hola en español = ola. house en inglés necesita un soplo suave, sin raspón de garganta. hat ≠ at. Pero hay H muda: hour, honest, honor. Lista corta de memoria; el resto, sopla.",
    listen: ["house", "hat", "hello", "have", "hour", "honest", "hat", "at"],
    yg: "house",
  },
  {
    min: 3,
    tag: "B1 · R",
    title: "La R inglesa no vibra",
    body: "No es RR ni la R suave de “pero” al inicio. La punta de la lengua se encoge atrás, sin golpear. red, right, very, three. Si ruedas la R, te oyen extranjero al segundo. work / word / world son [wer-], no “guork”.",
    listen: ["red", "right", "very", "three", "work", "word", "world", "car"],
    yg: "very",
  },
  {
    min: 3,
    tag: "B1 · números",
    title: "13 vs 30: cambia el GOLPE",
    body: "thirteen = golpea el FINAL (thir-TEEN). thirty = golpea el INICIO (THIR-ty). Igual: 14/40, 15/50, 16/60. En teléfono y precios esto confunde más que TH. Oye la frase, no el número suelto.",
    listen: ["thirteen", "thirty", "fourteen", "forty", "fifteen", "fifty", "sixteen", "sixty"],
    yg: "thirteen",
  },
  {
    min: 3,
    tag: "B1 · memoria",
    title: "woman / women / clothes",
    body: "woman (una) ≈ [wúmən]. women (varias) ≈ [wímin] — no “wómen”. clothes (ropa) ≈ [klouz], casi como close el verbo; no “cló-zes”. thought [thot] ≠ taught [tot]. Tres minas de oro para hispanohablantes.",
    listen: ["woman", "women", "clothes", "close", "thought", "taught", "I taught English", "I thought so"],
    yg: "women",
  },
  {
    min: 3,
    tag: "B1 · finales 2",
    title: "bag ≠ back: la última se VOZ o no",
    body: "Si la última consonante “canta” (con voz en la garganta) cambia la palabra: bag / back, cab / cap, his / hiss, said vs set. El español a veces apaga el final. Toca la garganta: back no zumba, bag sí.",
    listen: ["bag", "back", "cab", "cap", "his", "hiss", "said", "set"],
    yg: "bag",
  },
  {
    min: 3,
    tag: "B1 · calco",
    title: "Frases que delatan traducción",
    body: "No es fonética, pero se oye en B1: I have 25 years → I'm 25. I am agree → I agree. Explain me → Explain it to me. People is → People are. Depend of → It depends on. Si las dices “bien pronunciadas” pero así, igual suenan a español.",
    listen: ["I'm 25", "I agree", "Explain it to me", "People are waiting", "It depends on you"],
  },
  {
    min: 3,
    tag: "B1 · ¿ya llego?",
    title: "Checklist de oído B1 (este lab)",
    body: "Esto NO es el B1 de Cambridge (faltan gramática, lectura y writing). En ESTE lab, B1 es: distingues ship/sheep y cap/cape; TH y V te salen; usas I've + participio; 40 verbos irregulares sin congelarte; marcas el golpe en deVElop. Si eso te sale, el lab hizo su parte. El resto es hablar con gente y oír inglés real 10 min al día.",
    listen: ["ship", "sheep", "I've done it", "develop"],
  },
  {
    min: 4,
    tag: "B2 · americano",
    title: "La T en el medio se ablanda (flap)",
    body: "water, better, city, got it: la T entre vocales suena casi D suave (como la R suave de “pero”, no una T española). No es “mal inglés”: es USA. En YouGlish oye water. Si la T te sale muy dura, suenas más a libro que a conversación.",
    listen: ["water", "better", "city", "got it", "I got it"],
    yg: "water",
  },
  {
    min: 4,
    tag: "B2 · reducción",
    title: "gonna, wanna, gotta, should've",
    body: "going to → gonna. want to → wanna. got to → gotta. should have → should've [shúdəv]. Es informal; no lo escribas en un correo serio. Sí tienes que OÍRLO: si esperas las tres palabras enteras, te pierdes en series y reuniones.",
    listen: ["going to", "gonna", "want to", "wanna", "I should've asked", "I've got to go"],
    yg: "gonna",
  },
  {
    min: 4,
    tag: "B2 · unir",
    title: "Las palabras se pegan",
    body: "consonante + vocal: an apple ≈ a-napple. go out ≈ gowout. I agree mete una Y: ai-yagrí. saw it puede meter una W o R según acento. Si hablas palabra-espacio-palabra, suenas robot. Habla en grupos: I-WANT-to-GO.",
    listen: ["an apple", "go out", "I agree", "pick it up", "check it out"],
    yg: "check it out",
  },
  {
    min: 4,
    tag: "B2 · acento de frase",
    title: "El golpe dice el significado",
    body: "I wanted TEA (no café) vs I WANTED tea (sí lo pedí). En español también enfatizas, pero en inglés el resto se aplasta más. Preguntas sí/no suben un poco al final; What's your name? suele bajar. No cantes todas igual.",
    listen: ["I wanted tea", "Are you ready?", "What do you do?", "I live in Ecuador"],
  },
  {
    min: 4,
    tag: "B2 · finales duros",
    title: "asked, worlds, sixth",
    body: "Pediste, mundos, sexto: varios sonidos seguidos al final. Practica LENTO: ask + t. world + z. six + th. Nadie nace diciendo asked; los nativos también lo reducen, pero algo se oye. Si lo saltas del todo, parece another word.",
    listen: ["ask", "asked", "world", "worlds", "six", "sixth"],
    yg: "asked",
  },
  {
    min: 4,
    tag: "B2 · SH CH J",
    title: "ship / chip / jeep",
    body: "SH = aire (ship, she, English). CH = T+SH (chip, check). J = D+ZH (jeep, job, just). Hispanohablante mezcla chip y ship, o dice “llop” por job. Mini drill: she / cheap / jeep.",
    listen: ["ship", "chip", "jeep", "she", "cheap", "job", "just"],
    yg: "chip",
  },
  {
    min: 4,
    tag: "B2 · sílabas",
    title: "Palabras que se “comen” una sílaba",
    body: "comfortable ≈ CÓMF-ter-bəl (no com-for-ta-ble). chocolate, vegetable, interesting, family, camera, every, favorite, probably, actually. El español quiere cada vocal. El inglés las aplasta. Si las deletreas al hablar, suenas a libro.",
    listen: ["comfortable", "chocolate", "vegetable", "interesting", "family", "camera", "every", "favorite", "probably", "actually"],
    yg: "comfortable",
  },
  {
    min: 4,
    tag: "B2 · didja",
    title: "did you / don't you / would you",
    body: "did you ≈ dídyə o dídja. don't you ≈ dóun-chu. would you ≈ wúdyə. got you ≈ gácha. What are you…? ≈ wádəyə. No es vago: es cómo se pega T/D + Y. Si esperas “did + you” enteros, no entiendes preguntas rápidas.",
    listen: ["Did you see it?", "Don't you think so?", "Would you help me?", "What are you doing?", "Got you"],
    yg: "did you",
  },
  {
    min: 4,
    tag: "B2 · to",
    title: "have to, used to, supposed to",
    body: "have to ≈ háfta (la V se vuelve F). used to (antes) ≈ yúustə, no “yúzd tu”. supposed to ≈ səpóustə. want to ya lo viste: wanna. Son el pegamento de planes y hábitos; si las lees letra por letra, el oído real te gana.",
    listen: ["I have to go", "I used to live there", "I'm supposed to call", "I want to try"],
    yg: "used to",
  },
  {
    min: 4,
    tag: "B2 · of",
    title: "of vs off, than vs then",
    body: "of se aplasta [əv] o casi [ə]: a cup of tea. off se queda [oof/aaf]: turn it off. than (comparar) ≈ [dhən] floja; then (entonces) ≈ [dhen]. lot of → lotta. kind of → kinda. out of → outta. Informal de oído, no de correo.",
    listen: ["a cup of tea", "turn it off", "bigger than this", "And then I left", "a lot of work", "kind of"],
    yg: "kind of",
  },
  {
    min: 4,
    tag: "B2 · NG",
    title: "sing no es sin: la NG",
    body: "sing, thing, going: la N y la G se funden atrás (como que te tapas la nariz un poco), sin un G duro de “gato”. Si dices sin por sing, o going-gue, cambias la palabra. going en rápido ≈ góuin.",
    listen: ["sing", "sin", "thing", "thin", "going", "singer", "English"],
    yg: "singing",
  },
  {
    min: 4,
    tag: "B2 · Z",
    title: "has, was, zoo: a veces es Z",
    body: "La S escrita a menudo suena Z: has, is, was, his, goes, easy, because. zoo no es “soo”. Si todo te sale S sorda, suenas a castellano leído. Toca la garganta: easy zumba, ess no.",
    listen: ["has", "was", "is", "his", "goes", "easy", "zoo", "because"],
    yg: "easy",
  },
  {
    min: 4,
    tag: "B2 · hábito",
    title: "10 minutos de inglés real",
    body: "El sintetizador de esta página es claro de más. El B2 se gana oyendo gente de verdad: YouGlish (la palabrita + nativos), una serie CON subtítulos en inglés, un video corto sin pausar la primera vez. Meta: 10 min. Si solo usas el lab, tu oído se queda en “aula”.",
    listen: ["thought", "water", "gonna"],
    yg: "thought",
  },
];

ENLAB.prompts = [
  {
    title: "Tutor de pronunciación (tu nivel)",
    text: "Eres coach de pronunciación de inglés americano para hispanohablantes. Adapta A1–B2 según te diga. En cada frase: 1) transcripción fácil (ei, ii, ä, th, ə), 2) acento en MAYÚSCULAS, 3) error probable de hispanohablante, 4) una frase mínima para repetir 5 veces. Empieza preguntando mi nivel CEFR y qué quiero practicar.",
  },
  {
    title: "Drill de verbos (15 min)",
    text: "Soy hispanohablante. Dame 8 verbos irregulares de uso diario (no raros). Presente / pasado / participio, español, pronunciación fácil, y UNA frase: ayer (I + pasado) y UNA de experiencia (I have + participio). Mini quiz al final. Adapta al nivel que te diga (A1–B2).",
  },
  {
    title: "Conversación diaria (no entrevista tech)",
    text: "Practica conmigo inglés oral. Habla claro, frases cortas. Nivel B1 objetivo. Pregunta por mi día, planes, opiniones. Después de cada respuesta: corrige máximo 2 cosas (gramática o pronunciación descrita) y reformula en inglés natural. Empieza: What did you do yesterday?",
  },
  {
    title: "Explica esta vocal",
    text: "Explícame como a un hispanohablante POR QUÉ estas palabras no suenan igual. Usa sílaba cerrada, E muda, dos vocales, R y schwa. Palabras: [pégalas]. Transcripción fácil: ei, ii, ä, ou, ə. Sin IPA pesado.",
  },
  {
    title: "Ritmo y palabras débiles",
    text: "Marca en MAYÚSCULAS las palabras con golpe en esta frase y escribe cómo suenan to/of/can/the en forma débil. Frase: [pégala]. Luego una versión lenta y una versión de habla conectada.",
  },
  {
    title: "Diagnóstico B1 / B2 (oído)",
    text: "Soy hispanohablante. Nivel objetivo B1, quiero saber si me falta algo de oído/pronunciación para B1 o B2. No hagas un curso de gramática. Pregúntame 6 cosas cortas (TH, B/V, can/can't, I went vs I have, been, ritmo). Luego dime 3 agujeros y 3 drills de 5 minutos. Empieza.",
  },
];
