/* Extra: colocación CEFR, pares duros, role-plays ramificados */
window.ENLAB = window.ENLAB || {};

ENLAB.placementItems = [
  { min: 1, q: "How ___ you?", a: "are", opts: ["is", "are", "be"], prompt: "A1 · be", say: "How are you?", why: "I am / you are / she is." },
  { min: 1, q: "I ___ a coffee.", a: "want", opts: ["want", "wanting", "wanted"], prompt: "A1 · presente", say: "I want a coffee.", why: "Presente simple para deseos ahora." },
  { min: 1, q: "___ is your name?", a: "What", opts: ["Who", "What", "Where"], prompt: "A1 · pregunta", say: "What is your name?", why: "What = qué; Who = quién." },
  { min: 1, q: "There ___ two chairs.", a: "are", opts: ["is", "are", "have"], prompt: "A1 · there is/are", say: "There are two chairs.", why: "Plural → there are." },
  { min: 1, q: "She ___ to work.", a: "goes", opts: ["go", "goes", "going"], prompt: "A1 · 3ª persona", say: "She goes to work.", why: "He/she/it + -s." },
  { min: 2, q: "I ___ to the shop yesterday.", a: "went", opts: ["go", "goed", "went"], prompt: "A2 · pasado", say: "I went to the shop yesterday.", why: "go → went." },
  { min: 2, q: "___ you like tea?", a: "Do", opts: ["Are", "Do", "Have"], prompt: "A2 · Do you…?", say: "Do you like tea?", why: "Like es verbo; se pregunta con Do." },
  { min: 2, q: "I'm ___ the bus.", a: "on", opts: ["in", "on", "at"], prompt: "A2 · in/on/at", say: "I'm on the bus.", why: "on the bus / train." },
  { min: 2, q: "Can you ___ me a hand?", a: "give", opts: ["make", "give", "do"], prompt: "A2 · collocation", say: "Can you give me a hand?", why: "give me a hand, no make." },
  { min: 2, q: "I've ___ that film.", a: "seen", opts: ["saw", "seen", "see"], prompt: "A2 · present perfect", say: "I've seen that film.", why: "have + participio (seen)." },
  { min: 3, q: "If it rains, I ___ stay in.", a: "will", opts: ["will", "would", "won't to"], prompt: "B1 · 1st conditional", say: "If it rains, I will stay in.", why: "if + present, will." },
  { min: 3, q: "Could you ___ the deadline?", a: "push", opts: ["push", "put", "make"], prompt: "B1 · phrasal", say: "Could you push the deadline?", why: "push = mover la fecha." },
  { min: 3, q: "I wish I ___ more time.", a: "had", opts: ["have", "had", "would have"], prompt: "B1 · wish", say: "I wish I had more time.", why: "wish + pasado." },
  { min: 3, q: "She's in charge ___ the launch.", a: "of", opts: ["of", "for", "to"], prompt: "B1 · preposición", say: "She's in charge of the launch.", why: "in charge of." },
  { min: 3, q: "I'll get ___ to you today.", a: "back", opts: ["back", "up", "off"], prompt: "B1 · get back", say: "I'll get back to you today.", why: "get back to = responder." },
  { min: 4, q: "Had I known, I ___ have called.", a: "would", opts: ["will", "would", "can"], prompt: "B2 · inversión", say: "Had I known, I would have called.", why: "Had I known = If I had known." },
  { min: 4, q: "The issue was ___ by QA.", a: "flagged", opts: ["flagged", "flag", "flagging"], prompt: "B2 · pasiva", say: "The issue was flagged by QA.", why: "was + participio." },
  { min: 4, q: "I'd rather you ___ now.", a: "didn't", opts: ["don't", "didn't", "not"], prompt: "B2 · I'd rather you", say: "I'd rather you didn't smoke now.", why: "I'd rather + pasado." },
  { min: 4, q: "Neither option ___ ideal.", a: "is", opts: ["are", "is", "be"], prompt: "B2 · neither", say: "Neither option is ideal.", why: "neither + singular." },
  { min: 4, q: "We're ___ to ship on Friday.", a: "due", opts: ["due", "owed", "debt"], prompt: "B2 · due to", say: "We're due to ship on Friday.", why: "be due to + verb = previsto." },
  { min: 3, q: "She's been ___ here since March.", a: "working", opts: ["work", "working", "worked"], prompt: "B1 · present perfect continuous", say: "She's been working here since March.", why: "have/has been + -ing con since/for." },
  { min: 3, q: "Could you ___ me in the loop?", a: "keep", opts: ["keep", "put", "make"], prompt: "B1 · collocation", say: "Could you keep me in the loop?", why: "keep someone in the loop, no put." },
  { min: 4, q: "No sooner had we arrived ___ it started raining.", a: "than", opts: ["when", "than", "that"], prompt: "B2 · no sooner", say: "No sooner had we arrived than it started raining.", why: "no sooner … than (no when)." },
  { min: 4, q: "The proposal, ___ was late, still won.", a: "which", opts: ["who", "which", "what"], prompt: "B2 · relative", say: "The proposal, which was late, still won.", why: "which para cosas; comas = no restrictiva." },
];

(ENLAB.minimalPairs = ENLAB.minimalPairs || []).push(
  { a: "thin", b: "tin", ipaA: "/θɪn/", ipaB: "/tɪn/", sayA: "thin", sayB: "tin", hint: "/θ/ vs /t/ — lengua entre dientes", min: 2 },
  { a: "this", b: "dis", ipaA: "/ðɪs/", ipaB: "/dɪs/", sayA: "this", sayB: "dis", hint: "/ð/ sonora vs /d/", min: 2 },
  { a: "van", b: "ban", ipaA: "/væn/", ipaB: "/bæn/", sayA: "van", sayB: "ban", hint: "/v/ labiodental vs /b/", min: 2 },
  { a: "very", b: "berry", ipaA: "/ˈveri/", ipaB: "/ˈberi/", sayA: "very", sayB: "berry", hint: "v vs b al inicio", min: 2 },
  { a: "ship", b: "chip", ipaA: "/ʃɪp/", ipaB: "/tʃɪp/", sayA: "ship", sayB: "chip", hint: "/ʃ/ vs /tʃ/", min: 2 },
  { a: "wash", b: "watch", ipaA: "/wɑʃ/", ipaB: "/wɑtʃ/", sayA: "wash", sayB: "watch", hint: "final /ʃ/ vs /tʃ/", min: 2 },
  { a: "cot", b: "caught", ipaA: "/kɑt/", ipaB: "/kɔːt/", sayA: "cot", sayB: "caught", hint: "US cot–caught: /ɑ/ vs /ɔ/", min: 3 },
  { a: "staff", b: "starf", ipaA: "/stæf/", ipaB: "/stɑːf/", sayA: "staff", sayB: "staff", hint: "US /æ/ vs UK /ɑː/ en staff", min: 3 },
  { a: "dance", b: "dahnce", ipaA: "/dæns/", ipaB: "/dɑːns/", sayA: "dance", sayB: "dance", hint: "US /æ/ vs UK /ɑː/ en dance", min: 3 },
  { a: "can't", b: "cahnt", ipaA: "/kænt/", ipaB: "/kɑːnt/", sayA: "can't", sayB: "can't", hint: "US can't /æ/ vs UK /ɑː/", min: 3 },
  { a: "tomato", b: "tomahto", ipaA: "/təˈmeɪtoʊ/", ipaB: "/təˈmɑːtəʊ/", sayA: "tomato", sayB: "tomato", hint: "US /eɪ/ vs UK /ɑː/ en tomato", min: 3 },
  { a: "schedule", b: "shedule", ipaA: "/ˈskedʒuːl/", ipaB: "/ˈʃedjuːl/", sayA: "schedule", sayB: "schedule", hint: "US /sk/ vs UK /ʃ/ en schedule", min: 3 },
  { a: "bath", b: "bahth", ipaA: "/bæθ/", ipaB: "/bɑːθ/", sayA: "bath", sayB: "bath", hint: "US /æ/ vs UK /ɑː/ en bath", min: 3 },
  { a: "either", b: "eyether", ipaA: "/ˈiðər/", ipaB: "/ˈaɪðə/", sayA: "either", sayB: "either", hint: "US /i/ vs UK /aɪ/ en either", min: 3 },
  { a: "vitamin", b: "vittamin", ipaA: "/ˈvaɪtəmɪn/", ipaB: "/ˈvɪtəmɪn/", sayA: "vitamin", sayB: "vitamin", hint: "US /aɪ/ vs UK /ɪ/ en vitamin", min: 3 },
  { a: "garage", b: "garridge", ipaA: "/ɡəˈrɑʒ/", ipaB: "/ˈɡærɑːʒ/", sayA: "garage", sayB: "garage", hint: "US final stress vs UK /ˈɡærɑːʒ/", min: 3 },
  { a: "leisure", b: "lezhure", ipaA: "/ˈliːʒər/", ipaB: "/ˈleʒə/", sayA: "leisure", sayB: "leisure", hint: "US /iː/ vs UK /e/ en leisure", min: 3 },
  { a: "advert", b: "ədvert", ipaA: "/ædvərˈtaɪzmənt/", ipaB: "/ədˈvɜːtɪsmənt/", sayA: "advertisement", sayB: "advertisement", hint: "US stress -TISE- vs UK ad-VER-tis-ment", min: 3 },
  { a: "vase", b: "vahz", ipaA: "/veɪs/", ipaB: "/vɑːz/", sayA: "vase", sayB: "vase", hint: "US /eɪ/ vs UK /ɑː/ en vase", min: 3 },
  { a: "route", b: "rowt", ipaA: "/rut/", ipaB: "/raʊt/", sayA: "route", sayB: "route", hint: "US often /rut/ vs UK /raʊt/", min: 3 }
);

(ENLAB.roleplays = ENLAB.roleplays || []).push(
  {
    id: "branch-late",
    min: 2,
    title: "Llegas tarde (ramas)",
    es: "Elige cómo responder. Tres giros.",
    turns: [
      { a: "You're late. What happened?", b: "Sorry — the train was delayed.", bOpts: ["Sorry — the train was delayed.", "Traffic was terrible. I should have left earlier.", "I lost track of time. It won't happen again."] },
      { a: "Can you still join the meeting?", b: "Yes. Give me two minutes to sit down.", bOpts: ["Yes. Give me two minutes to sit down.", "I'll join on video from the lobby.", "Start without me; I'll catch up."] },
      { a: "Please message next time.", b: "Will do. Thanks for waiting.", bOpts: ["Will do. Thanks for waiting.", "Understood. I'll text if I'm running late.", "Fair point. I'll set an earlier alarm."] },
    ],
  },
  {
    id: "branch-feedback",
    min: 3,
    title: "Feedback difícil (ramas)",
    es: "Tu manager comenta un error. Tú eliges el tono.",
    turns: [
      { a: "This report missed the deadline. Walk me through it.", b: "I underestimated the data cleanup. Here's my plan.", bOpts: ["I underestimated the data cleanup. Here's my plan.", "I should have flagged the blocker on Monday.", "You're right. I dropped the ball and I own it."] },
      { a: "What changes next week?", b: "I'll send a mid-week checkpoint so we can adjust.", bOpts: ["I'll send a mid-week checkpoint so we can adjust.", "I'll pair with Ana on the numbers before I write.", "I'll cut scope if the data is late again."] },
      { a: "Anything you need from me?", b: "A clearer priority if two launches collide.", bOpts: ["A clearer priority if two launches collide.", "Fifteen minutes on Wednesday to review a draft.", "Nothing right now — I'll update you Friday."] },
    ],
  },
  {
    id: "branch-hotel",
    min: 2,
    title: "Hotel: problema (ramas)",
    es: "Recepción. Tú pides una solución.",
    turns: [
      { a: "How can I help you?", b: "The air conditioning in 412 isn't working.", bOpts: ["The air conditioning in 412 isn't working.", "Could I change rooms? The street is too loud.", "I think you charged me twice for parking."] },
      { a: "I'm sorry about that. What would you prefer?", b: "A quieter room if you have one tonight.", bOpts: ["A quieter room if you have one tonight.", "A fan and a discount on tonight is fine.", "Just send maintenance as soon as you can."] },
      { a: "I can do that. Anything else?", b: "Could breakfast start at seven instead of eight?", bOpts: ["Could breakfast start at seven instead of eight?", "No, that's all. Thank you.", "A late checkout would help a lot."] },
    ],
  },
  {
    id: "branch-pharmacy",
    min: 2,
    title: "Farmacia (ramas)",
    es: "El farmacéutico pregunta. Tú eliges qué pedir.",
    turns: [
      { a: "Hi. What can I help you with?", b: "I need something for a sore throat.", bOpts: ["I need something for a sore throat.", "Do you have this prescription in stock?", "I'm looking for allergy tablets, non-drowsy."] },
      { a: "Any allergies I should know about?", b: "I'm allergic to penicillin.", bOpts: ["I'm allergic to penicillin.", "No known allergies.", "Only a mild lactose intolerance."] },
      { a: "This should help. Twice a day after food.", b: "Got it. How much is it?", bOpts: ["Got it. How much is it?", "Can I take it with coffee?", "Is there a cheaper generic?"] },
    ],
  },
  {
    id: "branch-airport-delay",
    min: 3,
    title: "Vuelo retrasado (ramas)",
    es: "Mostrador de la aerolínea. Tú decides el tono.",
    turns: [
      { a: "I'm sorry — flight 440 is delayed three hours.", b: "Can you rebook me on the next available flight?", bOpts: ["Can you rebook me on the next available flight?", "Is there compensation for a delay this long?", "I'll wait, but I need a meal voucher."] },
      { a: "I can put you on the 9 p.m. or overnight.", b: "The 9 p.m. works if my bag moves with me.", bOpts: ["The 9 p.m. works if my bag moves with me.", "Overnight is fine. Please confirm a hotel.", "I'll take whatever gets me there today."] },
      { a: "Done. Here's your new boarding pass.", b: "Thank you. Which gate should I go to?", bOpts: ["Thank you. Which gate should I go to?", "Could you also send the change by email?", "Is the lounge still available with this ticket?"] },
    ],
  },
  {
    id: "branch-restaurant-bill",
    min: 2,
    title: "La cuenta (ramas)",
    es: "Camarero. Tú eliges cómo pedir la cuenta.",
    turns: [
      { a: "How was everything?", b: "Great, thanks. Could we get the check?", bOpts: ["Great, thanks. Could we get the check?", "The salmon was perfect. We'll take the bill.", "Good, but we waited a bit long for dessert."] },
      { a: "Together or split?", b: "Split it two ways, please.", bOpts: ["Split it two ways, please.", "One bill is fine. I'll get it.", "Can you put the drinks on a separate check?"] },
      { a: "Card or cash?", b: "Card, please. And could I have a receipt?", bOpts: ["Card, please. And could I have a receipt?", "Cash. Keep the change.", "Contactless if you take it."] },
    ],
  },
  {
    id: "branch-job-screen",
    min: 3,
    title: "Pantalla de empleo (ramas)",
    es: "Recruiter. Tú eliges el tono de la entrevista corta.",
    turns: [
      { a: "Walk me through a recent win.", b: "I cut onboarding time by a week with a clearer checklist.", bOpts: ["I cut onboarding time by a week with a clearer checklist.", "I shipped a messy launch and owned the postmortem.", "I unblocked two teams by writing the API notes."] },
      { a: "Why this role?", b: "I want to practice English in a real team, not just in class.", bOpts: ["I want to practice English in a real team, not just in class.", "The product is close to what I already ship.", "I'm ready for more client-facing work."] },
      { a: "Any questions for me?", b: "What does a strong first ninety days look like?", bOpts: ["What does a strong first ninety days look like?", "How do you give feedback on writing?", "What's the mix of meetings versus deep work?"] },
    ],
  },
  {
    id: "branch-neighbor-noise",
    min: 2,
    title: "Vecino ruidoso (ramas)",
    es: "Pasillo. Tú eliges cómo pedir silencio.",
    turns: [
      { a: "Hey — everything okay?", b: "Hi. The music is quite loud after ten. Could you turn it down?", bOpts: ["Hi. The music is quite loud after ten. Could you turn it down?", "Sorry to bother you. I have an early start tomorrow.", "Could we agree on quiet hours after ten?"] },
      { a: "I didn't realize. Is it that late?", b: "It's half past ten. Headphones would help a lot.", bOpts: ["It's half past ten. Headphones would help a lot.", "Yeah — I start work at seven.", "No rush tonight, but weeknights are hard."] },
      { a: "Got it. I'll keep it down.", b: "Thanks. I appreciate it.", bOpts: ["Thanks. I appreciate it.", "Thank you. Sleep well.", "Great. Knock if I'm ever too loud too."] },
    ],
  },
  {
    id: "branch-standup-blocker",
    min: 3,
    title: "Standup: bloqueo (ramas)",
    es: "Daily. Tú eliges cómo reportar el bloqueo.",
    turns: [
      { a: "Any blockers?", b: "I'm blocked on the staging key. I pinged IT an hour ago.", bOpts: ["I'm blocked on the staging key. I pinged IT an hour ago.", "QA found a flake. I'm pairing with Ana after this.", "No blocker — I'll ship the draft by noon."] },
      { a: "Need someone else?", b: "If IT doesn't reply by eleven, I'll need a backup env.", bOpts: ["If IT doesn't reply by eleven, I'll need a backup env.", "A fifteen-minute huddle with backend would unblock me.", "I can continue on docs until the key lands."] },
      { a: "I'll follow up. Anything else?", b: "That's it. Thanks.", bOpts: ["That's it. Thanks.", "I'll post a note in the channel when I'm unblocked.", "Could you flag it in the standup notes?"] },
    ],
  },
  {
    id: "branch-gp-visit",
    min: 2,
    title: "Consulta médica (ramas)",
    es: "Médico. Tú eliges cómo describir el síntoma.",
    turns: [
      { a: "What brings you in today?", b: "I've had a sore throat for three days.", bOpts: ["I've had a sore throat for three days.", "I keep getting dizzy when I stand up.", "It's a cough that gets worse at night."] },
      { a: "Any fever or allergies?", b: "No fever. I'm allergic to penicillin.", bOpts: ["No fever. I'm allergic to penicillin.", "A mild fever last night. No known allergies.", "I don't think so. I take ibuprofen already."] },
      { a: "I'll prescribe a spray. Rest and fluids.", b: "How often should I use it?", bOpts: ["How often should I use it?", "When should I come back if it doesn't improve?", "Is there a generic that's cheaper?"] },
    ],
  },
  {
    id: "branch-bank-hold",
    min: 3,
    title: "Banco: cargo extraño (ramas)",
    es: "Agente. Tú eliges cómo reclamar el cargo.",
    turns: [
      { a: "How can I help you today?", b: "There's a charge I don't recognize from Tuesday.", bOpts: ["There's a charge I don't recognize from Tuesday.", "My card was declined at the supermarket.", "I'd like to freeze the card while I travel."] },
      { a: "I can see a hold from a petrol station. Was that you?", b: "No. Please reverse it and send a new card.", bOpts: ["No. Please reverse it and send a new card.", "That might be me — I filled up on Tuesday.", "I'm not sure. Can you read the merchant name?"] },
      { a: "Done. Anything else on the account?", b: "That's all. Thank you.", bOpts: ["That's all. Thank you.", "Please text me when the new card ships.", "Could you raise the daily limit for next week?"] },
    ],
  },
  {
    id: "branch-landlord-leak",
    min: 2,
    title: "Fuga en el piso (ramas)",
    es: "Portero. Tú eliges cómo pedir arreglo.",
    turns: [
      { a: "What's going on upstairs?", b: "There's a leak under the kitchen sink.", bOpts: ["There's a leak under the kitchen sink.", "The heating hasn't come on since Friday.", "The lock on the street door is sticking."] },
      { a: "I can send someone this afternoon or tomorrow morning.", b: "This afternoon, please. I'll be home after four.", bOpts: ["This afternoon, please. I'll be home after four.", "Tomorrow morning works if they text first.", "It's urgent — the floor is getting wet."] },
      { a: "I'll put you down. Keep a bucket under it.", b: "Will do. Thanks for coming quickly.", bOpts: ["Will do. Thanks for coming quickly.", "Could you also check the stopcock?", "Great. I'll send a photo to the group chat."] },
    ],
  },
  {
    id: "branch-client-scope",
    min: 3,
    title: "Cliente: más alcance (ramas)",
    es: "Call. Tú eliges cómo negociar el extra.",
    turns: [
      { a: "Can we add a second dashboard before Friday?", b: "We can, if we drop the PDF export this sprint.", bOpts: ["We can, if we drop the PDF export this sprint.", "Not by Friday without extra hours. I can quote that.", "Let's ship the first dashboard and schedule the second."] },
      { a: "The board really wants both.", b: "Then I need a written change request and a new date.", bOpts: ["Then I need a written change request and a new date.", "I can do a thin version of both if QA is lighter.", "I'll ask the team and confirm in an hour."] },
      { a: "Fair. Send me options by end of day.", b: "I'll send two options with dates and cost.", bOpts: ["I'll send two options with dates and cost.", "You'll have a one-pager before five.", "I'll loop in finance so the quote is official."] },
    ],
  }
);

(ENLAB.dictation = ENLAB.dictation || []).push(
  { en: "Had I known about the delay, I would have flagged it sooner.", min: 4, es: "De haber sabido del retraso, lo habría avisado antes." },
  { en: "Neither proposal is viable without a longer support window.", min: 4, es: "Ninguna propuesta es viable sin una ventana de soporte más larga." },
  { en: "I'd rather you didn't share the draft until legal has signed off.", min: 4, es: "Preferiría que no compartieras el borrador hasta que legal dé el visto bueno." },
  { en: "We're due to ship on Friday provided QA signs off tonight.", min: 4, es: "Está previsto enviar el viernes si QA da el OK esta noche." },
  { en: "The issue was flagged by QA, not invented by the client.", min: 4, es: "El problema lo marcó QA, no lo inventó el cliente." },
  { en: "Could you walk me through the numbers one more time?", min: 4, es: "¿Me explicas los números una vez más?" },
  { en: "If I were you, I'd push the deadline rather than ship half-done.", min: 4, es: "Yo en tu lugar movería la fecha en vez de enviar a medias." },
  { en: "Please keep me in the loop if the scope starts to slip again.", min: 4, es: "Mantenme al tanto si el alcance vuelve a resbalar." },
  { en: "Were I in your position, I'd escalate before the client calls.", min: 4, es: "Yo en tu lugar escalaría antes de que llame el cliente." },
  { en: "The numbers were double-checked, yet the total still doesn't add up.", min: 4, es: "Los números se verificaron dos veces y el total no cuadra." },
  { en: "I'd sooner miss the party than ship a half-tested build.", min: 4, es: "Prefiero perderme la fiesta a enviar un build a medias." },
  { en: "Not until legal signs off should we send that wording.", min: 4, es: "Hasta que legal no dé el OK no enviamos ese texto." },
  { en: "She suggested that we postpone rather than rush the demo.", min: 4, es: "Sugirió posponer en vez de apresurar el demo." },
  { en: "Little did we know the API had a hard rate limit.", min: 4, es: "Ni nos imaginábamos que la API tenía un límite duro." },
  { en: "It's high time we wrote the runbook instead of relying on chat.", min: 4, es: "Ya es hora de escribir el runbook en vez de depender del chat." },
  { en: "Should the vendor slip again, we'll need a fallback supplier.", min: 4, es: "Si el proveedor se retrasa otra vez, hará falta un plan B." },
  { en: "Scarcely had we boarded when the gate closed behind us.", min: 4, es: "Apenas habíamos abordado cuando cerraron la puerta." },
  { en: "Were the numbers to slip, we'd have to renegotiate the retainer.", min: 4, es: "Si los números cayeran, habría que renegociar el retainer." },
  { en: "I'd just as soon wait as send an unreviewed draft.", min: 4, es: "Prefiero esperar a enviar un borrador sin revisar." },
  { en: "On no account should we promise a date we can't meet.", min: 4, es: "En ningún caso prometemos una fecha que no podemos cumplir." },
  { en: "The board would rather we delayed than launched half-baked.", min: 4, es: "La junta preferiría retrasar a lanzar a medias." },
  { en: "Much as I like the design, it doesn't meet the brief.", min: 4, es: "Por más que me guste el diseño, no cumple el brief." },
  { en: "Hardly anyone had read the appendix, yet they voted yes.", min: 4, es: "Casi nadie había leído el anexo y aun así votaron sí." },
  { en: "Should you need anything, ping me rather than waiting until Friday.", min: 4, es: "Si necesitas algo, escríbeme en vez de esperar al viernes." }
);

(ENLAB.emailSpeak = ENLAB.emailSpeak || []).push(
  {
    min: 3,
    tone: "formal",
    subject: "Request for reference — Maya Chen",
    from: "You",
    body: "Dear Ms. Alvarez,\n\nI am writing to request a professional reference for Maya Chen, who reported to you from 2022 to 2024. She is applying for a senior analyst role and has authorized me to contact you. A short paragraph by Friday would be greatly appreciated.\n\nKind regards,\nAlex Kim\nRecruiting",
    say: "Dear Ms. Alvarez. I am writing to request a professional reference for Maya Chen, who reported to you from twenty twenty two to twenty twenty four. She is applying for a senior analyst role and has authorized me to contact you. A short paragraph by Friday would be greatly appreciated. Kind regards, Alex Kim, Recruiting.",
    reply: "I would be glad to provide a reference. I will send it by Thursday.",
    es: "Pedir referencia formal de Maya Chen antes del viernes.",
    qs: [
      { q: "¿Sobre quién piden referencia?", a: "Maya Chen", opts: ["Maya Chen", "Ms. Alvarez", "Alex Kim"] },
      { q: "¿Para cuándo?", a: "Friday", opts: ["Monday", "Friday", "next month"] },
      { q: "¿Tono del email?", a: "formal", opts: ["informal", "formal", "casual"] },
    ],
  },
  {
    min: 3,
    tone: "informal",
    subject: "Thanks for covering standup",
    from: "You",
    body: "Hey Sam,\n\nThanks for running standup yesterday — I was stuck in a dentist chair. Notes look great. I owe you coffee.\n\nAlex",
    say: "Hey Sam. Thanks for running standup yesterday. I was stuck in a dentist chair. Notes look great. I owe you coffee. Alex.",
    reply: "No worries! Dentist wins. Coffee Thursday?",
    es: "Gracias informal por cubrir el standup.",
    qs: [
      { q: "¿Quién cubrió el standup?", a: "Sam", opts: ["Sam", "the dentist", "HR"] },
      { q: "¿Por qué faltó Alex?", a: "dentist", opts: ["vacation", "dentist", "flight delay"] },
      { q: "¿Tono del email?", a: "informal", opts: ["formal", "informal", "legal"] },
    ],
  },
  {
    min: 4,
    tone: "formal",
    subject: "Complaint — invoice #1209 billed twice",
    from: "Accounts payable",
    body: "Dear Sir or Madam,\n\nI am writing to dispute invoice #1209, which appears twice on our March statement. Please confirm a credit of $1,840 or provide evidence of two separate deliveries.\n\nYours faithfully,\nPriya Nair\nAccounts payable",
    say: "Dear Sir or Madam. I am writing to dispute invoice one two zero nine, which appears twice on our March statement. Please confirm a credit of one thousand eight hundred forty dollars or provide evidence of two separate deliveries. Yours faithfully, Priya Nair, Accounts payable.",
    reply: "We apologize. A credit note will be issued today.",
    es: "Reclamo formal: factura cobrada dos veces.",
    qs: [
      { q: "¿Número de factura?", a: "#1209", opts: ["#8842", "#1209", "#440"] },
      { q: "¿Qué piden?", a: "a credit", opts: ["a refund in cash", "a credit", "a new product"] },
      { q: "¿Tono del email?", a: "formal", opts: ["informal", "formal", "chat"] },
    ],
  },
  {
    min: 3,
    tone: "informal",
    subject: "Quick thank-you — Friday's demo",
    from: "You",
    body: "Hey team,\n\nJust a note: Friday's demo landed well. The client smiled at the slow-motion clip. Nice work, especially Jordan on the live data.\n\nLet's debrief Monday 10.\nAlex",
    say: "Hey team. Just a note. Friday's demo landed well. The client smiled at the slow-motion clip. Nice work, especially Jordan on the live data. Let's debrief Monday at ten. Alex.",
    reply: "Thanks! I'll grab a room for Monday.",
    es: "Gracias informal por el demo del viernes.",
    qs: [
      { q: "¿Qué salió bien?", a: "Friday's demo", opts: ["the invoice", "Friday's demo", "the flight"] },
      { q: "¿Quién destacó?", a: "Jordan", opts: ["Jordan", "the client only", "HR"] },
      { q: "¿Tono del email?", a: "informal", opts: ["formal", "informal", "legal"] },
    ],
  },
  {
    min: 3,
    tone: "formal",
    subject: "Request to reschedule Tuesday's review",
    from: "You",
    body: "Dear Ms. Patel,\n\nWould it be possible to move Tuesday's review to Wednesday afternoon? A client workshop overran and I will not have the deck ready. I can send a one-page summary tonight.\n\nKind regards,\nAlex Kim",
    say: "Dear Ms. Patel. Would it be possible to move Tuesday's review to Wednesday afternoon? A client workshop overran and I will not have the deck ready. I can send a one-page summary tonight. Kind regards, Alex Kim.",
    reply: "Wednesday at three works. Please send the summary tonight.",
    es: "Pedir mover la review al miércoles. Resumen esta noche.",
    qs: [
      { q: "¿Qué piden mover?", a: "Tuesday's review", opts: ["Tuesday's review", "the flight", "payroll"] },
      { q: "¿Qué envían esta noche?", a: "a one-page summary", opts: ["the full deck", "a one-page summary", "nothing"] },
      { q: "¿Tono del email?", a: "formal", opts: ["informal", "formal", "chat"] },
    ],
  },
  {
    min: 3,
    tone: "informal",
    subject: "Docs are in the shared folder",
    from: "You",
    body: "Hey,\n\nDropped the Q3 notes in the shared folder. Nothing fancy — just the decisions from Friday. Yell if the link 404s.\n\nAlex",
    say: "Hey. Dropped the Q three notes in the shared folder. Nothing fancy — just the decisions from Friday. Yell if the link four oh fours. Alex.",
    reply: "Got them. Thanks!",
    es: "Aviso informal: notas Q3 en la carpeta.",
    qs: [
      { q: "¿Qué subió?", a: "Q3 notes", opts: ["Q3 notes", "invoices", "passwords"] },
      { q: "¿De qué reunión?", a: "Friday", opts: ["Monday", "Friday", "next month"] },
      { q: "¿Tono del email?", a: "informal", opts: ["formal", "informal", "legal"] },
    ],
  },
  {
    min: 4,
    tone: "formal",
    subject: "Notice of planned maintenance — Sunday 02:00",
    from: "Platform",
    body: "Dear customer,\n\nWe will perform planned maintenance on Sunday from 02:00 to 04:00 UTC. The dashboard may be unavailable. No action is required on your side.\n\nYours faithfully,\nPlatform team",
    say: "Dear customer. We will perform planned maintenance on Sunday from two a.m. to four a.m. UTC. The dashboard may be unavailable. No action is required on your side. Yours faithfully, Platform team.",
    reply: "Thank you for the notice. We will warn our on-call.",
    es: "Aviso formal de mantenimiento domingo 2:00 UTC.",
    qs: [
      { q: "¿Qué día?", a: "Sunday", opts: ["Friday", "Sunday", "Monday"] },
      { q: "¿Qué puede fallar?", a: "the dashboard", opts: ["email only", "the dashboard", "payroll"] },
      { q: "¿Tono del email?", a: "formal", opts: ["informal", "formal", "slack"] },
    ],
  },
  {
    min: 3,
    tone: "informal",
    subject: "Coffee after the retro?",
    from: "You",
    body: "Hey team,\n\nAnyone up for coffee after retro? My treat. I'll grab a table at the usual place around 4:30.\n\nAlex",
    say: "Hey team. Anyone up for coffee after retro? My treat. I'll grab a table at the usual place around four thirty. Alex.",
    reply: "I'm in. See you there.",
    es: "Invitar a café informal después de la retro.",
    qs: [
      { q: "¿Cuándo?", a: "after retro", opts: ["before standup", "after retro", "Sunday"] },
      { q: "¿Quién invita?", a: "Alex", opts: ["the client", "Alex", "HR"] },
      { q: "¿Tono del email?", a: "informal", opts: ["formal", "informal", "legal"] },
    ],
  },
  {
    min: 3,
    tone: "formal",
    subject: "Apology — missed Tuesday's call",
    from: "You",
    body: "Dear Mr. Ortiz,\n\nPlease accept my apologies for missing Tuesday's call. A production incident overran and I should have sent a note sooner. I have attached a one-page recap and I am free Wednesday or Thursday after 3 p.m.\n\nKind regards,\nAlex Kim",
    say: "Dear Mr. Ortiz. Please accept my apologies for missing Tuesday's call. A production incident overran and I should have sent a note sooner. I have attached a one-page recap and I am free Wednesday or Thursday after three p.m. Kind regards, Alex Kim.",
    reply: "Thank you. Thursday at four works.",
    es: "Disculpa formal por faltar a la llamada del martes.",
    qs: [
      { q: "¿Qué se perdió?", a: "Tuesday's call", opts: ["Tuesday's call", "the flight", "payroll"] },
      { q: "¿Qué adjuntan?", a: "a one-page recap", opts: ["the full deck", "a one-page recap", "invoices"] },
      { q: "¿Tono del email?", a: "formal", opts: ["informal", "formal", "chat"] },
    ],
  },
  {
    min: 3,
    tone: "informal",
    subject: "Running five minutes late",
    from: "You",
    body: "Hey,\n\nStuck in the lift. Start without me — I'll be there in five.\n\nAlex",
    say: "Hey. Stuck in the lift. Start without me. I'll be there in five. Alex.",
    reply: "No stress. We saved you a seat.",
    es: "Aviso informal: llego cinco minutos tarde.",
    qs: [
      { q: "¿Dónde está?", a: "the lift", opts: ["the lift", "the airport", "home"] },
      { q: "¿Qué pide?", a: "start without me", opts: ["cancel", "start without me", "wait an hour"] },
      { q: "¿Tono del email?", a: "informal", opts: ["formal", "informal", "legal"] },
    ],
  },
  {
    min: 4,
    tone: "formal",
    subject: "Data processing addendum — signature requested",
    from: "Legal",
    body: "Dear customer,\n\nPlease find attached the data processing addendum for review. Kindly return a signed copy by Friday so we can complete onboarding. Do not hesitate to raise any questions with legal@example.com.\n\nYours faithfully,\nLegal team",
    say: "Dear customer. Please find attached the data processing addendum for review. Kindly return a signed copy by Friday so we can complete onboarding. Do not hesitate to raise any questions with legal at example dot com. Yours faithfully, Legal team.",
    reply: "We will review and return it by Thursday.",
    es: "Pedir firma formal del addendum de datos.",
    qs: [
      { q: "¿Qué adjuntan?", a: "data processing addendum", opts: ["invoices", "data processing addendum", "passwords"] },
      { q: "¿Para cuándo la firma?", a: "Friday", opts: ["Monday", "Friday", "next month"] },
      { q: "¿Tono del email?", a: "formal", opts: ["informal", "formal", "slack"] },
    ],
  },
  {
    min: 3,
    tone: "informal",
    subject: "Notes from the 1:1",
    from: "You",
    body: "Hey Priya,\n\nDropped our 1:1 notes in the doc — action items at the top. Ping me if I missed the bit about the vendor.\n\nAlex",
    say: "Hey Priya. Dropped our one-on-one notes in the doc. Action items at the top. Ping me if I missed the bit about the vendor. Alex.",
    reply: "Looks good. Vendor note is there.",
    es: "Notas informal del 1:1 en el doc.",
    qs: [
      { q: "¿Dónde están las notas?", a: "in the doc", opts: ["in email only", "in the doc", "on paper"] },
      { q: "¿Qué va arriba?", a: "action items", opts: ["jokes", "action items", "the agenda from last year"] },
      { q: "¿Tono del email?", a: "informal", opts: ["formal", "informal", "legal"] },
    ],
  }
);

(ENLAB.listenPassages = ENLAB.listenPassages || []).push(
  {
    min: 4,
    title: "Cambio de alcance",
    text: "The client asked for a second dashboard before Friday. We can do it if we drop the PDF export this sprint, or we quote extra hours. I'll send two options with dates and cost by five.",
    qs: [
      { q: "¿Qué pidió el cliente?", a: "a second dashboard", opts: ["a second dashboard", "a hotel room", "a refund"] },
      { q: "¿Qué se puede recortar?", a: "the PDF export", opts: ["the PDF export", "payroll", "the flight"] },
      { q: "¿Para cuándo las opciones?", a: "by five", opts: ["Monday", "by five", "next month"] },
    ],
  },
  {
    min: 3,
    title: "Aviso de mantenimiento",
    text: "We will perform planned maintenance on Sunday from two a.m. to four a.m. UTC. The dashboard may be unavailable. No action is required on your side.",
    qs: [
      { q: "¿Qué día?", a: "Sunday", opts: ["Friday", "Sunday", "Monday"] },
      { q: "¿Qué puede fallar?", a: "the dashboard", opts: ["email only", "the dashboard", "payroll"] },
      { q: "¿Qué debe hacer el cliente?", a: "nothing", opts: ["reboot now", "nothing", "call support at two a.m."] },
    ],
  },
  {
    min: 4,
    title: "Postmortem corto",
    text: "The outage lasted fourteen minutes. The trigger was a bad config push, not a vendor issue. We'll add a canary and a rollback checklist before the next release.",
    qs: [
      { q: "¿Cuánto duró?", a: "fourteen minutes", opts: ["four hours", "fourteen minutes", "two days"] },
      { q: "¿Cuál fue el disparador?", a: "a bad config push", opts: ["a vendor issue", "a bad config push", "a power cut"] },
      { q: "¿Qué van a añadir?", a: "a canary and a rollback checklist", opts: ["more meetings", "a canary and a rollback checklist", "a new logo"] },
    ],
  }
);

(ENLAB.writingPrompts = ENLAB.writingPrompts || []).push(
  {
    id: "email-decline",
    type: "email",
    title: "Decline a meeting politely",
    min: 3,
    prompt: "Decline Tuesday's review. Offer Wednesday and a one-page summary tonight.",
    model: "Dear Ms. Patel,\n\nWould it be possible to move Tuesday's review to Wednesday afternoon? A client workshop overran and I will not have the deck ready. I can send a one-page summary tonight.\n\nKind regards,\n[Name]",
    checklist: [
      { id: "tone", label: "Tone: polite, professional", weight: 2 },
      { id: "length", label: "Length: 3–5 sentences", weight: 1 },
      { id: "connectors", label: "Would it be possible, due to / overran", weight: 2 },
      { id: "action", label: "Offers an alternative time and a summary", weight: 2 },
    ],
    hints: ["would it be possible", "I can send", "kind regards"],
  },
  {
    id: "slack-estimate",
    type: "slack",
    title: "Give a time estimate",
    min: 3,
    prompt: "Slack: say when the draft will land and what you're blocked on.",
    model: "Draft by noon if the staging key lands. If IT is still quiet at eleven I'll switch to docs and ping you.",
    checklist: [
      { id: "tone", label: "Tone: informal but specific", weight: 2 },
      { id: "length", label: "Length: 1–2 sentences", weight: 1 },
      { id: "connectors", label: "if / by noon", weight: 2 },
      { id: "context", label: "Names the blocker or fallback", weight: 2 },
    ],
    hints: ["by noon", "if", "ping"],
  },
  {
    id: "email-intro-client",
    type: "email",
    title: "Introduce a teammate to a client",
    min: 3,
    prompt: "Short intro email: you, your teammate, and why you're writing.",
    model: "Dear Ms. Alvarez,\n\nI'm copying Jordan Chen, who will own the weekly numbers going forward. Please send scheduling notes to both of us.\n\nKind regards,\n[Name]",
    checklist: [
      { id: "tone", label: "Tone: formal, clear", weight: 2 },
      { id: "length", label: "Length: 2–4 sentences", weight: 1 },
      { id: "connectors", label: "I'm copying / going forward", weight: 2 },
      { id: "action", label: "Says who does what next", weight: 2 },
    ],
    hints: ["I'm copying", "going forward", "kind regards"],
  },
  {
    id: "slack-incident",
    type: "slack",
    title: "Incident update",
    min: 3,
    prompt: "Slack update during an incident: status, impact, next check-in.",
    model: "Login is down for EU — we're rolling back the 10:12 config. Next update in ten minutes. No action needed from support yet.",
    checklist: [
      { id: "tone", label: "Tone: calm, factual", weight: 2 },
      { id: "length", label: "Length: 1–2 sentences", weight: 1 },
      { id: "connectors", label: "we're / next update", weight: 1 },
      { id: "context", label: "Impact + next check-in", weight: 2 },
    ],
    hints: ["rolling back", "next update", "no action"],
  }
);
