/* Lote M: más escuchas, role-plays, emails hablados */
window.ENLAB = window.ENLAB || {};

(ENLAB.listenPassages = ENLAB.listenPassages || []).push(
  {
    min: 1,
    title: "En el bus",
    text: "This is the number 42 bus to downtown. The next stop is Main Street. Please have your fare ready. Thank you for riding with us.",
    qs: [
      { q: "¿Qué bus es?", a: "42", opts: ["12", "42", "84"] },
      { q: "¿Próxima parada?", a: "Main Street", opts: ["Airport", "Main Street", "Hospital"] },
      { q: "¿Qué debes tener listo?", a: "your fare", opts: ["your passport", "your fare", "a ticket home"] },
    ],
  },
  {
    min: 1,
    title: "Mensaje de voz",
    text: "Hey, it's me. I'm running ten minutes late. Start without me and order a coffee. See you soon.",
    qs: [
      { q: "¿Cuánto tarde?", a: "ten minutes", opts: ["two minutes", "ten minutes", "an hour"] },
      { q: "¿Qué puede hacer el otro?", a: "start without me", opts: ["cancel", "start without me", "go home"] },
      { q: "¿Qué puede pedir?", a: "a coffee", opts: ["a coffee", "a taxi", "lunch"] },
    ],
  },
  {
    min: 2,
    title: "Entrevista corta",
    text: "Thanks for coming in today. We'll start with a few questions about your experience. Then you'll meet the team. The whole process takes about one hour.",
    qs: [
      { q: "¿Con qué empiezan?", a: "questions about your experience", opts: ["a written test", "questions about your experience", "lunch"] },
      { q: "¿Qué pasa después?", a: "meet the team", opts: ["go home", "meet the team", "sign a contract"] },
      { q: "¿Cuánto dura?", a: "about one hour", opts: ["ten minutes", "about one hour", "all day"] },
    ],
  },
  {
    min: 2,
    title: "Farmacia",
    text: "Good morning. Do you have a prescription? Take one pill every eight hours with food. Call us if you feel worse.",
    qs: [
      { q: "¿Preguntan por…?", a: "a prescription", opts: ["a passport", "a prescription", "insurance only"] },
      { q: "¿Cada cuánto la pastilla?", a: "every eight hours", opts: ["every hour", "every eight hours", "once a week"] },
      { q: "¿Si empeoras?", a: "call us", opts: ["ignore it", "call us", "stop eating"] },
    ],
  },
  {
    min: 3,
    title: "Soporte técnico",
    text: "I see your account is locked. I'll reset your password and send a link to your email. Check spam if you don't see it in five minutes.",
    qs: [
      { q: "¿Qué pasa con la cuenta?", a: "it's locked", opts: ["it's deleted", "it's locked", "it's free"] },
      { q: "¿Qué envían?", a: "a link", opts: ["a package", "a link", "a phone call only"] },
      { q: "¿Si no llega el correo?", a: "check spam", opts: ["wait a week", "check spam", "buy a new laptop"] },
    ],
  },
  {
    min: 3,
    title: "Vecino ruidoso",
    text: "Hi, I'm your neighbor from 4B. The music is pretty loud tonight. Could you turn it down after ten? I have an early meeting.",
    qs: [
      { q: "¿De dónde es el vecino?", a: "4B", opts: ["1A", "4B", "the street"] },
      { q: "¿Qué pide?", a: "turn it down", opts: ["turn it up", "turn it down", "move out"] },
      { q: "¿Por qué?", a: "early meeting", opts: ["birthday party", "early meeting", "vacation"] },
    ],
  },
  {
    min: 4,
    title: "Negociación",
    text: "We like your proposal, but the timeline is tight. If you can deliver phase one by Friday, we'll sign today. Otherwise we need another week to review.",
    qs: [
      { q: "¿Qué les gusta?", a: "your proposal", opts: ["the price only", "your proposal", "the office"] },
      { q: "¿Condición para firmar hoy?", a: "deliver phase one by Friday", opts: ["work for free", "deliver phase one by Friday", "move to another city"] },
      { q: "Si no, ¿qué necesitan?", a: "another week", opts: ["another week", "a new CEO", "nothing"] },
    ],
  },
  {
    min: 4,
    title: "Podcast clip",
    text: "Today we're talking about habits. Small steps beat big plans. If you miss a day, don't quit — just start again tomorrow. Consistency wins.",
    qs: [
      { q: "¿Tema del clip?", a: "habits", opts: ["weather", "habits", "sports scores"] },
      { q: "¿Qué gana a planes grandes?", a: "small steps", opts: ["big plans", "small steps", "luck only"] },
      { q: "Si fallas un día, ¿qué hacer?", a: "start again tomorrow", opts: ["quit forever", "start again tomorrow", "buy a course"] },
    ],
  }
);

(ENLAB.roleplays = ENLAB.roleplays || []).push(
  {
    id: "airport",
    min: 2,
    title: "En el aeropuerto",
    es: "Tú preguntas en mostrador.",
    turns: [
      { a: "How can I help you?", b: "Where is gate twelve?" },
      { a: "Gate twelve is on your left.", b: "Is boarding open yet?" },
      { a: "Not yet. About twenty minutes.", b: "Thank you." },
    ],
  },
  {
    id: "restaurant",
    min: 2,
    title: "En el restaurante",
    es: "Tú pides la comida.",
    turns: [
      { a: "Are you ready to order?", b: "Yes. I'd like the chicken, please." },
      { a: "Anything to drink?", b: "Just water, please." },
      { a: "I'll bring that out soon.", b: "Could we have the check, please?" },
    ],
  },
  {
    id: "bank",
    min: 3,
    title: "En el banco",
    es: "Tú necesitas efectivo.",
    turns: [
      { a: "Good afternoon. What can I do for you?", b: "I'd like to withdraw some cash." },
      { a: "May I see your ID?", b: "Sure. Here you go." },
      { a: "How much would you like?", b: "Two hundred dollars, please." },
    ],
  },
  {
    id: "landlord",
    min: 3,
    title: "Con el casero",
    es: "Tú reportas un problema.",
    turns: [
      { a: "What's the issue?", b: "The sink is leaking." },
      { a: "When did it start?", b: "It started last night." },
      { a: "I'll send someone tomorrow.", b: "Thank you. I'll be home after five." },
    ],
  },
  {
    id: "performance",
    min: 4,
    title: "Revisión de desempeño",
    es: "Tú hablas con tu manager.",
    turns: [
      { a: "How do you think the quarter went?", b: "I hit my targets and helped the team ship on time." },
      { a: "What would you improve?", b: "I'd like to get better at presenting to clients." },
      { a: "Any support you need?", b: "Maybe a mentor or shadowing a senior rep." },
    ],
  },
  {
    id: "conflict",
    min: 4,
    title: "Desacuerdo en equipo",
    es: "Tú propones una solución.",
    turns: [
      { a: "We don't agree on the deadline.", b: "Let's list what's blocking us first." },
      { a: "QA needs two more days.", b: "Could we ship a hotfix and test the rest?" },
      { a: "That could work.", b: "I'll write a short plan and share it today." },
    ],
  },
  {
    id: "uber",
    min: 2,
    title: "En el Uber",
    es: "Tú hablas con el conductor.",
    turns: [
      { a: "Hi, are you going to Main Street?", b: "Yes, that's right." },
      { a: "Traffic is bad. It'll take twenty minutes.", b: "No problem. Could you turn on the AC?" },
      { a: "Sure. We're almost there.", b: "This is my stop. Thanks." },
    ],
  },
  {
    id: "return",
    min: 2,
    title: "Devolver en tienda",
    es: "Tú devuelves un producto.",
    turns: [
      { a: "Do you have the receipt?", b: "Yes. Here it is." },
      { a: "Was there a problem with it?", b: "It's the wrong size." },
      { a: "We can exchange it or refund you.", b: "I'd like to exchange it, please." },
    ],
  }
);

ENLAB.emailSpeak = [
  {
    min: 2,
    subject: "Meeting moved to 3 p.m.",
    from: "Sarah",
    body: "Hi team,\n\nQuick update: the sync is now at 3 p.m. Same link.\n\nThanks,\nSarah",
    say: "Hi team. Quick update. The sync is now at three p.m. Same link. Thanks, Sarah.",
    reply: "Thanks for the update. I'll be there at three.",
    es: "La junta se movió a las 3.",
    qs: [{ q: "¿A qué hora es ahora?", a: "3 p.m.", opts: ["10 a.m.", "3 p.m.", "6 p.m."] }],
  },
  {
    min: 2,
    subject: "Out of office today",
    from: "Mike",
    body: "Hi,\n\nI'm out of office today. I'll reply tomorrow morning.\n\nMike",
    say: "Hi. I'm out of office today. I'll reply tomorrow morning. Mike.",
    reply: "No problem. Talk tomorrow.",
    es: "Fuera de oficina hoy.",
    qs: [{ q: "¿Cuándo responde?", a: "tomorrow morning", opts: ["today", "tomorrow morning", "next week"] }],
  },
  {
    min: 3,
    subject: "Invoice attached",
    from: "Accounts",
    body: "Hello,\n\nPlease find the invoice attached. Payment is due in 15 days.\n\nRegards,\nAccounts",
    say: "Hello. Please find the invoice attached. Payment is due in fifteen days. Regards, Accounts.",
    reply: "Received. We'll process payment this week.",
    es: "Factura adjunta. Pago en 15 días.",
    qs: [{ q: "¿Plazo de pago?", a: "15 days", opts: ["5 days", "15 days", "60 days"] }],
  },
  {
    min: 3,
    subject: "Can you review this?",
    from: "Alex",
    body: "Hey,\n\nCan you review the doc by EOD? It's the Q3 plan.\n\nAlex",
    say: "Hey. Can you review the doc by EOD? It's the Q three plan. Alex.",
    reply: "Sure. I'll send feedback by five.",
    es: "¿Revisas el doc al cierre del día?",
    qs: [{ q: "¿Qué documento?", a: "Q3 plan", opts: ["Q3 plan", "vacation form", "password reset"] }],
  },
  {
    min: 3,
    subject: "Interview confirmation",
    from: "HR",
    body: "Dear candidate,\n\nYour interview is confirmed for Tuesday at 10 a.m. Please arrive ten minutes early.\n\nHR Team",
    say: "Dear candidate. Your interview is confirmed for Tuesday at ten a.m. Please arrive ten minutes early. HR Team.",
    reply: "Thank you. I'll be there at 9:50.",
    es: "Entrevista confirmada martes 10 a.m.",
    qs: [{ q: "¿Cuándo llegar?", a: "ten minutes early", opts: ["one hour early", "ten minutes early", "late is fine"] }],
  },
  {
    min: 3,
    subject: "Server maintenance tonight",
    from: "IT",
    body: "Team,\n\nWe'll restart the server at 11 p.m. Expect five minutes of downtime.\n\nIT",
    say: "Team. We'll restart the server at eleven p.m. Expect five minutes of downtime. IT.",
    reply: "Noted. I'll warn the client.",
    es: "Mantenimiento servidor 11 p.m.",
    qs: [{ q: "¿Cuánto downtime?", a: "five minutes", opts: ["five minutes", "five hours", "none"] }],
  },
  {
    min: 4,
    subject: "Follow-up on proposal",
    from: "Client",
    body: "Hi,\n\nWe reviewed your proposal. The price works, but we need a longer support window. Can you send an updated quote?\n\nBest,\nJamie",
    say: "Hi. We reviewed your proposal. The price works, but we need a longer support window. Can you send an updated quote? Best, Jamie.",
    reply: "Thanks, Jamie. I'll send an updated quote by Friday.",
    es: "Cliente pide ventana de soporte más larga.",
    qs: [{ q: "¿Qué piden cambiar?", a: "longer support window", opts: ["lower price only", "longer support window", "cancel project"] }],
  },
  {
    min: 2,
    subject: "Package delivered",
    from: "Shipping",
    body: "Your package was left at the front door. Tracking: 8842.\n\nThanks for shopping with us.",
    say: "Your package was left at the front door. Tracking: eight eight four two. Thanks for shopping with us.",
    reply: "Got it. I'll pick it up tonight.",
    es: "Paquete en la puerta.",
    qs: [{ q: "¿Dónde lo dejaron?", a: "front door", opts: ["front door", "neighbor", "post office only"] }],
  },
  {
    min: 2,
    subject: "Doctor appointment reminder",
    from: "Clinic",
    body: "Reminder: appointment tomorrow at 2:30 p.m. Reply C to confirm or call to reschedule.",
    say: "Reminder. Appointment tomorrow at two thirty p.m. Reply C to confirm or call to reschedule.",
    reply: "C. See you tomorrow.",
    es: "Cita médica mañana 2:30.",
    qs: [{ q: "¿Cómo confirmar?", a: "Reply C", opts: ["Reply C", "Pay online", "No reply needed"] }],
  },
  {
    min: 3,
    subject: "Welcome to the team",
    from: "Manager",
    body: "Welcome aboard!\n\nYour first day is Monday. HR will send your laptop. Lunch with the team at noon.\n\nSee you soon.",
    say: "Welcome aboard. Your first day is Monday. HR will send your laptop. Lunch with the team at noon. See you soon.",
    reply: "Thank you. I'm excited to join.",
    es: "Bienvenida. Primer día lunes.",
    qs: [{ q: "¿Primer día?", a: "Monday", opts: ["Friday", "Monday", "next month"] }],
  },
  {
    min: 4,
    subject: "Contract revision",
    from: "Legal",
    body: "Please review the attached revision. Clause 4 now covers data retention for 24 months. Sign by the 30th.\n\nLegal",
    say: "Please review the attached revision. Clause four now covers data retention for twenty four months. Sign by the thirtieth. Legal.",
    reply: "I'll review with my manager and reply by Thursday.",
    es: "Revisión contrato. Retención datos 24 meses.",
    qs: [{ q: "¿Retención de datos?", a: "24 months", opts: ["24 days", "24 months", "24 hours"] }],
  },
  {
    min: 3,
    subject: "Running late",
    from: "Colleague",
    body: "Stuck in traffic. Start the call without me — I'll join in 5.\n\nSorry!",
    say: "Stuck in traffic. Start the call without me. I'll join in five. Sorry.",
    reply: "No worries. We'll start and catch you up.",
    es: "Llega tarde 5 min. Empiecen sin él.",
    qs: [{ q: "¿Cuándo se une?", a: "in 5 minutes", opts: ["in 5 minutes", "never", "tomorrow"] }],
  },
  {
    min: 2,
    subject: "Thank you for coming in",
    from: "Clinic",
    body: "Hi,\n\nThanks for your visit today. Take the medication twice a day with food. Call us if you feel worse.\n\nClinic",
    say: "Hi. Thanks for your visit today. Take the medication twice a day with food. Call us if you feel worse. Clinic.",
    reply: "Thank you. I'll take it with breakfast and dinner.",
    es: "Medicamento dos veces al día con comida.",
    qs: [{ q: "¿Cada cuánto?", a: "twice a day", opts: ["once a week", "twice a day", "only at night"] }],
  },
  {
    min: 3,
    subject: "Hotel confirmation",
    from: "Reservations",
    body: "Your booking is confirmed for Friday and Saturday. Check-in after 3 p.m. Breakfast is included.\n\nReservations",
    say: "Your booking is confirmed for Friday and Saturday. Check-in after three p.m. Breakfast is included. Reservations.",
    reply: "Perfect. Could we request a quiet room?",
    es: "Reserva viernes y sábado. Check-in 3 p.m.",
    qs: [{ q: "¿Desayuno?", a: "included", opts: ["not included", "included", "extra fee"] }],
  },
  {
    min: 4,
    subject: "Action items from today",
    from: "PM",
    body: "Three action items: 1) Ship the hotfix today. 2) Update the client by 5. 3) Schedule a retro on Friday.\n\nThanks.",
    say: "Three action items. One: ship the hotfix today. Two: update the client by five. Three: schedule a retro on Friday. Thanks.",
    reply: "I'll take items one and two. Can you own the retro?",
    es: "Tres action items del día.",
    qs: [{ q: "¿Cuántos items?", a: "three", opts: ["one", "three", "ten"] }],
  },
  {
    min: 3,
    subject: "Password reset",
    from: "Security",
    body: "We reset your password at your request. The link expires in 30 minutes. Do not share it.\n\nSecurity",
    say: "We reset your password at your request. The link expires in thirty minutes. Do not share it. Security.",
    reply: "Got it. I'll reset it now.",
    es: "Reset de contraseña. Link 30 min.",
    qs: [{ q: "¿Expira en?", a: "30 minutes", opts: ["30 seconds", "30 minutes", "30 days"] }],
  },
];
