/* Lote S: pronunciación — mínimos pares, IPA, mapa US/UK */
window.ENLAB = window.ENLAB || {};

ENLAB.minimalPairs = [
  { a: "ship", b: "sheep", ipaA: "/ʃɪp/", ipaB: "/ʃiːp/", hint: "i corta vs i larga", min: 1, sayA: "ship", sayB: "sheep" },
  { a: "sit", b: "seat", ipaA: "/sɪt/", ipaB: "/siːt/", hint: "i vs ii", min: 1, sayA: "sit", sayB: "seat" },
  { a: "live", b: "leave", ipaA: "/lɪv/", ipaB: "/liːv/", hint: "vivir vs irse", min: 2, sayA: "I live here.", sayB: "I leave at six." },
  { a: "walk", b: "work", ipaA: "/wɔːk/", ipaB: "/wɜːrk/", hint: "aw vs er", min: 2, sayA: "walk", sayB: "work" },
  { a: "cat", b: "cut", ipaA: "/kæt/", ipaB: "/kʌt/", hint: "a vs ah", min: 1, sayA: "cat", sayB: "cut" },
  { a: "bad", b: "bed", ipaA: "/bæd/", ipaB: "/bed/", hint: "a vs e", min: 1, sayA: "bad", sayB: "bed" },
  { a: "pool", b: "pull", ipaA: "/puːl/", ipaB: "/pʊl/", hint: "u larga vs u corta", min: 2, sayA: "pool", sayB: "pull" },
  { a: "full", b: "fool", ipaA: "/fʊl/", ipaB: "/fuːl/", hint: "u corta vs u larga", min: 2, sayA: "full", sayB: "fool" },
  { a: "cap", b: "cape", ipaA: "/kæp/", ipaB: "/keɪp/", hint: "vocal corta vs larga", min: 1, sayA: "cap", sayB: "cape" },
  { a: "bit", b: "beat", ipaA: "/bɪt/", ipaB: "/biːt/", hint: "i vs ii", min: 1, sayA: "bit", sayB: "beat" },
  { a: "pin", b: "pen", ipaA: "/pɪn/", ipaB: "/pen/", hint: "i vs e", min: 1, sayA: "pin", sayB: "pen" },
  { a: "thin", b: "thing", ipaA: "/θɪn/", ipaB: "/θɪŋ/", hint: "n vs ng", min: 2, sayA: "thin", sayB: "thing" },
  { a: "sin", b: "sing", ipaA: "/sɪn/", ipaB: "/sɪŋ/", hint: "n vs ng", min: 2, sayA: "sin", sayB: "sing" },
  { a: "very", b: "berry", ipaA: "/ˈveri/", ipaB: "/ˈberi/", hint: "v vs b", min: 2, sayA: "very", sayB: "berry" },
  { a: "think", b: "sink", ipaA: "/θɪŋk/", ipaB: "/sɪŋk/", hint: "th vs s", min: 2, sayA: "think", sayB: "sink" },
  { a: "three", b: "tree", ipaA: "/θriː/", ipaB: "/triː/", hint: "th vs t", min: 2, sayA: "three", sayB: "tree" },
  { a: "west", b: "vest", ipaA: "/west/", ipaB: "/vest/", hint: "w vs v", min: 2, sayA: "west", sayB: "vest" },
  { a: "cheap", b: "jeep", ipaA: "/tʃiːp/", ipaB: "/dʒiːp/", hint: "ch vs j", min: 2, sayA: "cheap", sayB: "jeep" },
  { a: "rice", b: "rise", ipaA: "/raɪs/", ipaB: "/raɪz/", hint: "s vs z", min: 2, sayA: "rice", sayB: "rise" },
  { a: "fan", b: "van", ipaA: "/fæn/", ipaB: "/væn/", hint: "f vs v", min: 1, sayA: "fan", sayB: "van" },
  { a: "light", b: "right", ipaA: "/laɪt/", ipaB: "/raɪt/", hint: "l vs r", min: 2, sayA: "light", sayB: "right" },
  { a: "lake", b: "rake", ipaA: "/leɪk/", ipaB: "/reɪk/", hint: "l vs r", min: 2, sayA: "lake", sayB: "rake" },
  { a: "can", b: "can't", ipaA: "/kæn/", ipaB: "/kænt/", hint: "T final", min: 1, sayA: "I can go.", sayB: "I can't go." },
  { a: "world", b: "word", ipaA: "/wɜːrld/", ipaB: "/wɜːrd/", hint: "ld vs d", min: 3, sayA: "world", sayB: "word" },
  { a: "bird", b: "beard", ipaA: "/bɜːrd/", ipaB: "/bɪrd/", hint: "er vs ir", min: 3, sayA: "bird", sayB: "beard" },
  { a: "heart", b: "hurt", ipaA: "/hɑːrt/", ipaB: "/hɜːrt/", hint: "ar vs er", min: 3, sayA: "heart", sayB: "hurt" },
  { a: "walk", b: "woke", ipaA: "/wɔːk/", ipaB: "/woʊk/", hint: "aw vs o", min: 2, sayA: "walk", sayB: "woke" },
  { a: "man", b: "men", ipaA: "/mæn/", ipaB: "/men/", hint: "a vs e plural", min: 1, sayA: "man", sayB: "men" },
  { a: "bus", b: "boss", ipaA: "/bʌs/", ipaB: "/bɔːs/", hint: "u vs o", min: 2, sayA: "bus", sayB: "boss" },
  { a: "duck", b: "dog", ipaA: "/dʌk/", ipaB: "/dɔːɡ/", hint: "u vs o", min: 1, sayA: "duck", sayB: "dog" },
];

ENLAB.ipaWords = {
  hello: "/həˈloʊ/", world: "/wɜːrld/", through: "/θruː/", thought: "/θɔːt/",
  schedule: "/ˈskedʒuːl/", water: "/ˈwɔːtər/", better: "/ˈbetər/", internet: "/ˈɪntərnet/",
  comfortable: "/ˈkʌmftəbəl/", vegetable: "/ˈvedʒtəbəl/", interesting: "/ˈɪntrəstɪŋ/",
  pronunciation: "/prəˌnʌnsiˈeɪʃən/", development: "/dɪˈveləpmənt/", colleague: "/ˈkɑːliːɡ/",
  appointment: "/əˈpɔɪntmənt/", receipt: "/rɪˈsiːt/", queue: "/kjuː/", subtle: "/ˈsʌtəl/",
  rhythm: "/ˈrɪðəm/", algorithm: "/ˈælɡərɪðəm/", entrepreneur: "/ˌɑːntrəprəˈnɜːr/",
  architecture: "/ˈɑːrkɪtektʃər/", maintenance: "/ˈmeɪntənəns/", bureaucracy: "/bjʊˈrɑːkrəsi/",
  inevitably: "/ɪnˈevɪtəbli/", conscientious: "/ˌkɑːnʃiˈenʃəs/", hierarchy: "/ˈhaɪərɑːrki/",
  thorough: "/ˈθɜːroʊ/", February: "/ˈfebrueri/", library: "/ˈlaɪbreri/", probably: "/ˈprɑːbəbli/",
  basically: "/ˈbeɪsɪkli/", absolutely: "/ˈæbsəluːtli/", definitely: "/ˈdefɪnətli/",
  temperature: "/ˈtemprətʃər/", comfortable: "/ˈkʌmfərtəbəl/", particularly: "/pərˈtɪkjələrli/",
};

ENLAB.accentMap = [
  { word: "schedule", us: "/ˈskedʒuːl/", uk: "/ˈʃedjuːl/", usSay: "SKED-jool", ukSay: "SHED-yool", note: "SKED vs SHED" },
  { word: "tomato", us: "/təˈmeɪtoʊ/", uk: "/təˈmɑːtəʊ/", usSay: "tuh-MAY-toh", ukSay: "tuh-MAH-toh", note: "ay vs ah" },
  { word: "water", us: "/ˈwɔːtər/", uk: "/ˈwɔːtə/", usSay: "WAH-ter (r)", ukSay: "WAW-tuh", note: "R vs sin R" },
  { word: "advertisement", us: "/ˌædvərˈtaɪzmənt/", uk: "/ədˈvɜːtɪsmənt/", usSay: "ad-ver-TIZE-ment", ukSay: "ad-VERT-is-ment", note: "acento distinto" },
  { word: "route", us: "/ruːt/", uk: "/raʊt/", usSay: "root", ukSay: "rowt", note: "oo vs ow" },
  { word: "privacy", us: "/ˈpraɪvəsi/", uk: "/ˈprɪvəsi/", usSay: "PRY-vuh-see", ukSay: "PRIV-uh-see", note: "ai vs i" },
  { word: "garage", us: "/ɡəˈrɑːʒ/", uk: "/ˈɡærɑːʒ/", usSay: "guh-RAHZH", ukSay: "GAR-ahzh", note: "acento final" },
  { word: "vitamin", us: "/ˈvaɪtəmɪn/", uk: "/ˈvɪtəmɪn/", usSay: "VY-tuh-min", ukSay: "VIT-uh-min", note: "ai vs i" },
  { word: "mobile", us: "/ˈmoʊbəl/", uk: "/ˈmoʊbaɪl/", usSay: "MOH-bul", ukSay: "MOH-bile", note: "1 vs 2 sílabas final" },
  { word: "leisure", us: "/ˈliːʒər/", uk: "/ˈleʒə/", usSay: "LEE-zher", ukSay: "LEZH-uh", note: "ee vs e" },
  { word: "herb", us: "/ɜːrb/", uk: "/hɜːb/", usSay: "erb (h muda)", ukSay: "herb (h suena)", note: "H muda en US" },
  { word: "aluminum", us: "/əˈluːmɪnəm/", uk: "/ˌæljəˈmɪniəm/", usSay: "uh-LOO-mih-num", ukSay: "al-yuh-MIN-ee-um", note: "aluminium UK" },
  { word: "data", us: "/ˈdeɪtə/", uk: "/ˈdɑːtə/", usSay: "DAY-tuh", ukSay: "DAH-tuh", note: "ay vs ah" },
  { word: "either", us: "/ˈiːðər/", uk: "/ˈaɪðə/", usSay: "EE-ther", ukSay: "EYE-ther", note: "ee vs eye" },
  { word: "often", us: "/ˈɔːfən/", uk: "/ˈɒfən/", usSay: "AW-fen (T muda)", ukSay: "OF-en", note: "T a veces muda en US" },
  { word: "lieutenant", us: "/luːˈtenənt/", uk: "/lefˈtenənt/", usSay: "loo-TEN-unt", ukSay: "lef-TEN-unt", note: "lu vs lef" },
  { word: "progress", us: "/ˈprɑːɡres/ noun", uk: "/ˈprəʊɡres/ noun", usSay: "PRAH-gres", ukSay: "PROH-gres", note: "acento en PRO" },
  { word: "research", us: "/ˈriːsɜːrtʃ/", uk: "/rɪˈsɜːtʃ/", usSay: "REE-search", ukSay: "ri-SEARCH", note: "acento distinto" },
  { word: "address", us: "/əˈdres/ verb", uk: "/əˈdres/ verb", usSay: "uh-DRESS", ukSay: "uh-DRESS", note: "similar; noun varía" },
  { word: "clerk", us: "/klɜːrk/", uk: "/klɑːk/", usSay: "klurk", ukSay: "klark", note: "er vs ar" },
];
