/* Lote V: writing con rúbrica — emails, Slack, cover letters */
window.ENLAB = window.ENLAB || {};

ENLAB.writingPrompts = [
  {
    id: "email-late",
    type: "email",
    title: "Running late to meeting",
    min: 2,
    prompt: "Write a short email to your team. You're 15 minutes late because of traffic.",
    model: "Hi team,\n\nI'm running about 15 minutes late due to traffic. Please start without me — I'll join as soon as I arrive.\n\nSorry for the delay.\n\nBest,\n[Name]",
    checklist: [
      { id: "tone", label: "Tone: polite, professional", weight: 2 },
      { id: "length", label: "Length: 2–4 sentences", weight: 1 },
      { id: "connectors", label: "Connectors: due to, as soon as", weight: 1 },
      { id: "action", label: "Clear action: start without me", weight: 2 },
    ],
    hints: ["due to", "as soon as", "sorry for"],
  },
  {
    id: "email-followup",
    type: "email",
    title: "Follow up after interview",
    min: 3,
    prompt: "Thank the interviewer and mention one thing you discussed.",
    model: "Dear [Name],\n\nThank you for taking the time to speak with me today. I enjoyed learning more about the team and the roadmap we discussed.\n\nI remain very interested in the role and look forward to hearing from you.\n\nBest regards,\n[Name]",
    checklist: [
      { id: "tone", label: "Tone: warm, formal", weight: 2 },
      { id: "length", label: "Length: 3–5 sentences", weight: 1 },
      { id: "connectors", label: "Connectors: thank you for, look forward to", weight: 2 },
      { id: "specific", label: "Specific detail from interview", weight: 2 },
    ],
    hints: ["thank you for", "look forward to", "remains interested"],
  },
  {
    id: "slack-blocked",
    type: "slack",
    title: "Blocked on staging",
    min: 3,
    prompt: "Slack message: you're blocked on staging access. Ask for help.",
    model: "Hey team — I'm blocked on staging access for the login fix. Could someone grant it or point me to who owns permissions? Thanks!",
    checklist: [
      { id: "tone", label: "Tone: informal but clear", weight: 2 },
      { id: "length", label: "Length: 1–2 sentences", weight: 1 },
      { id: "connectors", label: "Direct ask: could someone", weight: 2 },
      { id: "context", label: "Context: what you're working on", weight: 2 },
    ],
    hints: ["blocked on", "could someone", "thanks"],
  },
  {
    id: "slack-ooo",
    type: "slack",
    title: "Out of office",
    min: 2,
    prompt: "Tell your team you'll be OOO tomorrow and who covers you.",
    model: "Heads up — I'll be OOO tomorrow. For urgent issues, ping @Maria. I'll catch up on Thursday.",
    checklist: [
      { id: "tone", label: "Tone: casual, informative", weight: 2 },
      { id: "length", label: "Length: 1–2 sentences", weight: 1 },
      { id: "connectors", label: "Heads up, for urgent", weight: 1 },
      { id: "cover", label: "Names backup person", weight: 2 },
    ],
    hints: ["heads up", "OOO", "catch up"],
  },
  {
    id: "cover-intro",
    type: "cover",
    title: "Cover letter opening",
    min: 3,
    prompt: "Opening paragraph: why this company and role.",
    model: "I am writing to apply for the Product Manager position at Acme Corp. With five years leading cross-functional teams in SaaS, I am excited by your mission to simplify payments for small businesses.",
    checklist: [
      { id: "tone", label: "Tone: confident, not arrogant", weight: 2 },
      { id: "length", label: "Length: 2–3 sentences", weight: 1 },
      { id: "connectors", label: "With X years, excited by", weight: 2 },
      { id: "fit", label: "Links your skills to their mission", weight: 2 },
    ],
    hints: ["I am writing to apply", "With X years", "excited by"],
  },
  {
    id: "cover-close",
    type: "cover",
    title: "Cover letter closing",
    min: 3,
    prompt: "Closing: availability and call to action.",
    model: "I would welcome the opportunity to discuss how my experience in agile delivery can support your Q3 launch. I am available for an interview at your convenience.\n\nSincerely,\n[Name]",
    checklist: [
      { id: "tone", label: "Tone: professional close", weight: 2 },
      { id: "length", label: "Length: 2 sentences + sign-off", weight: 1 },
      { id: "connectors", label: "would welcome, at your convenience", weight: 2 },
      { id: "cta", label: "Clear call to action", weight: 2 },
    ],
    hints: ["would welcome", "at your convenience", "Sincerely"],
  },
  {
    id: "email-complaint",
    type: "email",
    title: "Polite complaint",
    min: 3,
    prompt: "Email to hotel: room was noisy. Ask for partial refund.",
    model: "Dear Guest Services,\n\nThank you for hosting me. Unfortunately, I experienced significant noise from the adjacent room until 2 a.m., which affected my rest before an early flight.\n\nWould it be possible to arrange a partial refund or credit for a future stay?\n\nKind regards,\n[Name]",
    checklist: [
      { id: "tone", label: "Tone: firm but polite", weight: 2 },
      { id: "length", label: "Length: 3–4 sentences", weight: 1 },
      { id: "connectors", label: "Unfortunately, would it be possible", weight: 2 },
      { id: "ask", label: "Specific ask: refund or credit", weight: 2 },
    ],
    hints: ["unfortunately", "would it be possible", "kind regards"],
  },
  {
    id: "slack-praise",
    type: "slack",
    title: "Public praise",
    min: 2,
    prompt: "Praise a teammate publicly for helping you ship.",
    model: "Shout-out to @Alex for jumping on the login bug last night — we shipped on time because of you. 🙌",
    checklist: [
      { id: "tone", label: "Tone: genuine, positive", weight: 2 },
      { id: "length", label: "Length: 1 sentence", weight: 1 },
      { id: "connectors", label: "Shout-out, because of", weight: 1 },
      { id: "specific", label: "Names person and what they did", weight: 2 },
    ],
    hints: ["shout-out", "because of", "shipped"],
  },
];
