/* Lote O: 50 mensajes Slack / Teams — formal e informal */
window.ENLAB = window.ENLAB || {};
ENLAB.chatWork = [
  { tone: "informal", en: "Hey, quick update on the ticket.", es: "Update rápido del ticket.", say: "Hey, quick update on the ticket.", reply: "Thanks — what's the status?", min: 2 },
  { tone: "informal", en: "Can you hop on a quick call?", es: "¿Entras a una llamada rápida?", say: "Can you hop on a quick call?", reply: "Sure, give me two minutes.", min: 2 },
  { tone: "informal", en: "I'll ping you when it's ready.", es: "Te aviso cuando esté listo.", say: "I'll ping you when it's ready.", reply: "Sounds good.", min: 2 },
  { tone: "informal", en: "Sorry, I missed this thread.", es: "Perdón, se me pasó el hilo.", say: "Sorry, I missed this thread.", reply: "No worries — here's the summary.", min: 2 },
  { tone: "informal", en: "LGTM, ship it.", es: "Se ve bien, despliégalo.", say: "LGTM, ship it.", reply: "On it. Deploying now.", min: 3 },
  { tone: "informal", en: "Heads-up: deploy at five.", es: "Aviso: deploy a las cinco.", say: "Heads-up: deploy at five.", reply: "Got it. I'll watch the logs.", min: 3 },
  { tone: "informal", en: "I'm blocked on the API key.", es: "Estoy bloqueado con la API key.", say: "I'm blocked on the API key.", reply: "I'll send you one in DM.", min: 3 },
  { tone: "informal", en: "Can you review my PR?", es: "¿Revisas mi PR?", say: "Can you review my PR?", reply: "Yes, I'll look in an hour.", min: 2 },
  { tone: "informal", en: "Running five minutes late.", es: "Llego cinco min tarde.", say: "Running five minutes late.", reply: "No problem. We'll start without you.", min: 2 },
  { tone: "informal", en: "Who has the latest numbers?", es: "¿Quién tiene los números?", say: "Who has the latest numbers?", reply: "I do — posting in the channel.", min: 3 },
  { tone: "informal", en: "Let's sync after lunch.", es: "Nos sincronizamos después de comer.", say: "Let's sync after lunch.", reply: "Works for me.", min: 2 },
  { tone: "informal", en: "This is a false alarm.", es: "Falsa alarma.", say: "This is a false alarm.", reply: "Thanks for checking.", min: 3 },
  { tone: "informal", en: "I'll take the first shift.", es: "Yo cubro el primer turno.", say: "I'll take the first shift.", reply: "Thanks, I'll take the next one.", min: 3 },
  { tone: "informal", en: "Can someone cover me tomorrow?", es: "¿Me cubren mañana?", say: "Can someone cover me tomorrow?", reply: "I can — send me the handoff.", min: 3 },
  { tone: "informal", en: "We're green in staging.", es: "Staging en verde.", say: "We're green in staging.", reply: "Nice. Prod next?", min: 3 },
  { tone: "informal", en: "I pushed a hotfix.", es: "Metí un hotfix.", say: "I pushed a hotfix.", reply: "Seeing it. Monitoring now.", min: 3 },
  { tone: "informal", en: "Need eyes on this error.", es: "Necesito ojos en este error.", say: "Need eyes on this error.", reply: "Looking now.", min: 3 },
  { tone: "informal", en: "Brb, grabbing coffee.", es: "Vuelvo, voy por café.", say: "Brb, grabbing coffee.", reply: "Same here.", min: 2 },
  { tone: "informal", en: "Thread getting long — moving to a doc.", es: "Hilo largo — lo paso a doc.", say: "Thread getting long — moving to a doc.", reply: "Good idea. Link?", min: 3 },
  { tone: "informal", en: "Thanks for jumping in.", es: "Gracias por meterte.", say: "Thanks for jumping in.", reply: "Happy to help.", min: 2 },
  { tone: "formal", en: "Please find the report attached.", es: "Adjunto el informe.", say: "Please find the report attached.", reply: "Received. I'll review by EOD.", min: 3 },
  { tone: "formal", en: "Could you confirm receipt of this message?", es: "¿Confirma recepción?", say: "Could you confirm receipt of this message?", reply: "Confirmed. Thank you.", min: 3 },
  { tone: "formal", en: "I am writing to follow up on our meeting.", es: "Le escribo para dar seguimiento a la reunión.", say: "I am writing to follow up on our meeting.", reply: "Thank you. I will respond with next steps.", min: 4 },
  { tone: "formal", en: "Please let me know if you require further information.", es: "Avíseme si necesita más información.", say: "Please let me know if you require further information.", reply: "Will do. Thank you.", min: 4 },
  { tone: "formal", en: "We apologize for the inconvenience.", es: "Disculpamos las molestias.", say: "We apologize for the inconvenience.", reply: "Understood. When will it be resolved?", min: 3 },
  { tone: "formal", en: "The issue has been escalated to engineering.", es: "El caso se escaló a ingeniería.", say: "The issue has been escalated to engineering.", reply: "Thank you for the update.", min: 3 },
  { tone: "formal", en: "Kindly approve the change request.", es: "Apruebe la solicitud de cambio.", say: "Kindly approve the change request.", reply: "Approved. Proceed as planned.", min: 4 },
  { tone: "formal", en: "Per our agreement, delivery is scheduled for Friday.", es: "Según acuerdo, entrega el viernes.", say: "Per our agreement, delivery is scheduled for Friday.", reply: "Acknowledged.", min: 4 },
  { tone: "formal", en: "I would appreciate your feedback by Thursday.", es: "Agradecería su feedback el jueves.", say: "I would appreciate your feedback by Thursday.", reply: "You will have it Wednesday.", min: 4 },
  { tone: "formal", en: "Please refrain from sharing confidential data.", es: "No comparta datos confidenciales.", say: "Please refrain from sharing confidential data.", reply: "Understood.", min: 4 },
  { tone: "formal", en: "We are pleased to inform you that the contract was signed.", es: "Nos complace informar que firmaron el contrato.", say: "We are pleased to inform you that the contract was signed.", reply: "Excellent news.", min: 4 },
  { tone: "formal", en: "Could we schedule a call at your earliest convenience?", es: "¿Agendamos llamada cuando le convenga?", say: "Could we schedule a call at your earliest convenience?", reply: "Tuesday at ten works.", min: 4 },
  { tone: "formal", en: "Thank you for your prompt response.", es: "Gracias por responder pronto.", say: "Thank you for your prompt response.", reply: "You're welcome.", min: 3 },
  { tone: "formal", en: "The deployment window is approved for Sunday 2 a.m.", es: "Ventana de deploy aprobada domingo 2 a.m.", say: "The deployment window is approved for Sunday 2 a.m.", reply: "Noted. On-call will monitor.", min: 4 },
  { tone: "formal", en: "Please cc the legal team on this thread.", es: "Incluya a legal en el hilo.", say: "Please cc the legal team on this thread.", reply: "Done.", min: 4 },
  { tone: "informal", en: "Anyone free for a five-minute huddle?", es: "¿Alguien para un huddle de 5 min?", say: "Anyone free for a five-minute huddle?", reply: "I'm in.", min: 3 },
  { tone: "informal", en: "I'll loop in design.", es: "Meto a diseño.", say: "I'll loop in design.", reply: "Thanks.", min: 3 },
  { tone: "informal", en: "This unblocks me — thanks!", es: "Con esto ya puedo avanzar.", say: "This unblocks me — thanks!", reply: "Great to hear.", min: 2 },
  { tone: "informal", en: "Can we push standup to nine thirty?", es: "¿Movemos standup a 9:30?", say: "Can we push standup to nine thirty?", reply: "Fine by me.", min: 2 },
  { tone: "informal", en: "I'm OOO next week.", es: "Fuera la próxima semana.", say: "I'm OOO next week.", reply: "Got it. Enjoy.", min: 2 },
  { tone: "informal", en: "Let's table this for now.", es: "Lo dejamos pendiente.", say: "Let's table this for now.", reply: "Agreed.", min: 3 },
  { tone: "informal", en: "I'll draft something and share.", es: "Esbozo algo y comparto.", say: "I'll draft something and share.", reply: "Perfect.", min: 3 },
  { tone: "informal", en: "We need a decision today.", es: "Necesitamos decidir hoy.", say: "We need a decision today.", reply: "I'll weigh in by noon.", min: 3 },
  { tone: "informal", en: "Flagging this as urgent.", es: "Marco esto como urgente.", say: "Flagging this as urgent.", reply: "On it.", min: 3 },
  { tone: "formal", en: "As discussed, please see the updated timeline.", es: "Como acordamos, timeline actualizado.", say: "As discussed, please see the updated timeline.", reply: "Reviewed. Approved.", min: 4 },
  { tone: "formal", en: "We regret to inform you of a service interruption.", es: "Lamentamos informar interrupción del servicio.", say: "We regret to inform you of a service interruption.", reply: "Please share ETA for resolution.", min: 4 },
  { tone: "formal", en: "Your request has been assigned ticket number 4421.", es: "Su ticket es el 4421.", say: "Your request has been assigned ticket number 4421.", reply: "Thank you.", min: 3 },
  { tone: "formal", en: "Please confirm your availability for the audit.", es: "Confirme disponibilidad para la auditoría.", say: "Please confirm your availability for the audit.", reply: "I am available Thursday.", min: 4 },
  { tone: "formal", en: "We will proceed pending your approval.", es: "Procedemos sujeto a su aprobación.", say: "We will proceed pending your approval.", reply: "You have my approval.", min: 4 },
  { tone: "informal", en: "Nice work on the demo!", es: "¡Buen demo!", say: "Nice work on the demo!", reply: "Thanks — team effort.", min: 2 },
  { tone: "informal", en: "I'll be in meetings until three.", es: "En juntas hasta las tres.", say: "I'll be in meetings until three.", reply: "I'll async you the notes.", min: 2 },
  { tone: "informal", en: "Can you share the recording?", es: "¿Compartes la grabación?", say: "Can you share the recording?", reply: "Uploading now.", min: 2 },
  { tone: "informal", en: "We're rolling back.", es: "Hacemos rollback.", say: "We're rolling back.", reply: "I'll update the channel.", min: 3 },
  { tone: "informal", en: "Who's on call tonight?", es: "¿Quién está on-call?", say: "Who's on call tonight?", reply: "I am.", min: 2 },
  { tone: "formal", en: "Kindly advise if the deadline can be extended.", es: "Indique si se puede extender el plazo.", say: "Kindly advise if the deadline can be extended.", reply: "We can extend it by two days.", min: 4 },
  { tone: "formal", en: "Please find my availability below.", es: "Abajo mi disponibilidad.", say: "Please find my availability below.", reply: "Thursday afternoon works.", min: 3 },
  { tone: "informal", en: "Can you take a look at the logs?", es: "¿Miras los logs?", say: "Can you take a look at the logs?", reply: "On it — sending a screenshot.", min: 3 },
  { tone: "informal", en: "I'll circle back after the call.", es: "Vuelvo después de la llamada.", say: "I'll circle back after the call.", reply: "Sounds good.", min: 3 },
  { tone: "formal", en: "We look forward to your response.", es: "Quedamos atentos a su respuesta.", say: "We look forward to your response.", reply: "You will hear from us by Friday.", min: 3 },
  { tone: "informal", en: "That's a wrap for today.", es: "Cerramos por hoy.", say: "That's a wrap for today.", reply: "Nice work, everyone.", min: 2 },
];
